fossasia/open-event-organizer-android

src/app/app.component.ts
src/pages/events/events.ts
src/pages/login/login.ts

**Fixes #58**: Logout Navigation Drawer Page access removed from the Login Page
**Changes Done:**
- Disabled the MenuController on the Login Page by adding  `this.menuCtrl.enable(true);`
- Enabled the MenuController back when user logs in by  `this.menuCtrl.enable(true);`
- Changed the order of execution in logout method to fix an inconsistent state of Navigation Drawer. Functionality remains unaffected.

fix: fixed Navigation Drawer appearing on Login Page

---

.editorconfig

Fixes #86 
- Use 4 spaces instead of 2

fix: Editor Config following Android specific guidelines

---

app/src/main/java/org/fossasia/openevent/app/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesActivity.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailActivityPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailsActivity.java
app/src/main/java/org/fossasia/openevent/app/events/EventsActivity.java
app/src/main/java/org/fossasia/openevent/app/events/EventsListAdapter.java

Fixes #119 
- Make Event Parcelable
- Share event to EventDetailActivity to show initial information while ticket info loads

feat: Share event parcel to display initial info

---

app/src/main/java/org/fossasia/openevent/app/common/binding/BindingAdapters.java

Fixes #158 
Add null or empty check in binding adapter with Uri parse to ensure correct uri encoding

fix: Add null check in image load binding adapter

---

app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailPresenter.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java

fixes #194
There are two async calls on event detail page. hence progressbar was getting hidden by one of them while other is in progress.

Fixes progressbar on event detail page

---

app/src/main/java/org/fossasia/openevent/app/common/BaseFragment.java
app/src/main/java/org/fossasia/openevent/app/data/EventRepository.java
app/src/main/java/org/fossasia/openevent/app/data/db/DatabaseRepository.java
app/src/main/java/org/fossasia/openevent/app/data/db/contract/IDatabaseRepository.java
app/src/main/java/org/fossasia/openevent/app/data/models/Attendee.java
app/src/main/java/org/fossasia/openevent/app/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/data/models/Order.java
app/src/main/java/org/fossasia/openevent/app/data/models/Ticket.java
app/src/main/java/org/fossasia/openevent/app/event/EventContainerFragment.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/contract/IAttendeesPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/contract/IEventDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/events/EventDetailActivity.java
app/src/main/java/org/fossasia/openevent/app/events/EventListActivity.java
app/src/main/java/org/fossasia/openevent/app/events/EventsListAdapter.java
app/src/main/java/org/fossasia/openevent/app/qrscan/ScanQRActivity.java
app/src/test/java/org/fossasia/openevent/app/db/SimpleModelTest.java
app/src/test/java/org/fossasia/openevent/app/model/EventRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java

- Change DatabaseRepository API to be more general and less BaseModel specific
- Remove constraint on BaseModel for models used in FastAdapter and rather extend from AbstractItem
- Remove Parcelable models and propagate data through keys
- Remove raw types and add correct generics in FastAdapter classes
Fixes #203

feat: Change API according FastAdapter and DBFlow

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/PresenterModule.java
app/src/main/java/org/fossasia/openevent/app/data/UtilModel.java
app/src/main/java/org/fossasia/openevent/app/data/contract/IUtilModel.java
app/src/main/java/org/fossasia/openevent/app/login/LoginActivity.java
app/src/main/java/org/fossasia/openevent/app/login/LoginPresenter.java
app/src/main/java/org/fossasia/openevent/app/login/contract/ILoginView.java
app/src/main/java/org/fossasia/openevent/app/utils/Constants.java
app/src/main/res/layout/content_login.xml
app/src/test/java/org/fossasia/openevent/app/presenter/LoginPresenterTest.java

Fixes #209 : Autocomplete email text input

---

app/src/main/java/org/fossasia/openevent/app/qrscan/ScanQRActivity.java

Fixes #229 
- Dispose barcode emitter on destroy

fix: Memory leak in ScanQRActivity

---

app/src/main/java/org/fossasia/openevent/app/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/events/EventListActivity.java
app/src/main/java/org/fossasia/openevent/app/events/EventsListAdapter.java
app/src/main/java/org/fossasia/openevent/app/events/EventsPresenter.java
app/src/main/java/org/fossasia/openevent/app/events/viewholders/EventsHeaderViewHolder.java
app/src/main/java/org/fossasia/openevent/app/utils/DateUtils.java
app/src/main/res/layout/event_layout.xml
app/src/main/res/layout/event_subheader_layout.xml
app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventsPresenterTest.java

- Implements comparable interface on event model
- sorts events in order of live, upcoming and past
- for both past, lately ended will be before in list
- for both live, lately started will be before in list
- for both upcoming earliest will be before
- Implements sticky header adapter on eventslistadapter
- Modifies event layout
fixes #152

feat: Group events into live, past and upcoming

---

app/src/main/res/drawable/bottom_nav_tint.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/values/colors.xml

- sets icon and text color according to material design guideline.
- removes unused bottom navigation selectable color drawable.
fixes #282

fix: drawer item styling

---

app/src/main/java/org/fossasia/openevent/app/main/MainActivity.java
app/src/main/res/menu/activity_main_drawer.xml

- hides event related sub menus when no event is selected
- adds divider between sub menus and the events menu
fixes #293

fix: modify navigation drawer

---

app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java
app/src/main/java/org/fossasia/openevent/app/data/contract/ILoginModel.java
app/src/main/java/org/fossasia/openevent/app/data/models/User.java
app/src/main/java/org/fossasia/openevent/app/login/LoginPresenter.java
app/src/test/java/org/fossasia/openevent/app/model/LoginModelTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/LoginPresenterTest.java

- method `LoginModel::login` is modified to just get access token
- new method `LoginModel::isPreviousUser` is added to check different user login
- method `LoginPresenter::login` is modified accordingly to clear database on different user login and starts data loading after that only.
fixes #252

fix: clearing database on different user login

---

app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java
app/src/main/java/org/fossasia/openevent/app/utils/JWTUtils.java
app/src/test/java/org/fossasia/openevent/app/model/LoginModelTest.java
app/src/test/java/org/fossasia/openevent/app/utils/JWTUtilsTest.java

Fixes #305
- Extract identifier from JWT
- Add test for identifier extraction
- Use identifier to discern the user is same or not
- Fix tests

feat: Use JWT to match existing and authenticated user

---

app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/analyser/ChartAnalyser.java

To be merged after #389 
- Add save logic for ticket presenter and chart analyzer
- Show saved data on rotation
- Refresh the chart layout on force reload
Fixes #396

feat: Persist dashboard on rotation

---

app/src/main/AndroidManifest.xml
app/src/main/res/values-v19/styles.xml
app/src/main/res/values-v23/styles.xml
app/src/main/res/values/styles.xml

- Fine tune styles
- Move v21 style (Lollipop) to v19 (Kitkat)
- Use different Main Style for QR Scan Activity
Fixes #427

fix: Make QR Scan Activity Translucent

---

app/src/main/java/org/fossasia/openevent/app/common/data/repository/AbstractObservableBuilder.java
app/src/test/java/org/fossasia/openevent/app/unit/model/AttendeeRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/unit/model/EventRepositoryTest.java

- on forced data request, load data from the server and update the local database and emit from the local database
- build method of AbstractObservableBuilder is modified to do the same.
- fixes missing fields in the emitted data due to relationships with ids in the models.
fixes #435

fix: emit data always from the local database

---

app/config/checkstyle.xml

- `NewlineAtEndOfFile` is disabled in check style config
fixes #488
(the commit is made from windows)

fix: modify check style

---

app/src/main/res/layout/main_nav_header.xml

- added background attribute to the container in the XML layout
fixes #520

fix: default color to the event detail palette

---

app/src/main/res/layout/reset_password_by_token_fragment.xml

feat: Password Toggle added

---

app/src/main/java/org/fossasia/openevent/app/common/app/binding/BindingAdapters.java

Fixes #624
Changes: makes the default quantity zero if the quantity field in create new ticket form is left blank 
which prevents the app from crashing when the value is erased.

fix: App crashes when value in quantity textview is erased (#624)

---

app/src/main/java/org/fossasia/openevent/app/common/app/binding/BindingAdapters.java

Fixes #627
Changes: Use Utils.isEmpty() instead of directly using == operator to prevent the application from crashing when the value in price text view is erased.

fix: App crash in Ticket Create Layout (#627)

---

app/src/main/java/org/fossasia/openevent/app/common/utils/core/DateUtils.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/CreateTicketPresenter.java
app/src/test/java/org/fossasia/openevent/app/robo/ui/FragmentInstanceTest.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/TicketCreatePresenterTest.java

Fixes #614 
Changes: Alligned the ticket's default sale end time with the front end.
The front end adds 10 days to the current date for the default end time. If the number of days left for the event is less than 10 days then it is set to the end date of the event.

fix: Allign ticket's default sale end time with frontend

---

app/src/main/res/layout/ticket_detail_layout.xml
app/src/main/res/values/strings.xml

Fixes #653 
Changes: Minumum and maximum order details are made visible to the user

feat: Show order details with other ticket details (#653)

---

app/proguard-rules.pro

Fixes #668 
Changes: New Progaurd Rule added for class `org.conscrypt.**`
Not applicable

fix: Resolved Progaurd execution failure

---

app/src/main/java/org/fossasia/openevent/app/common/app/di/component/AppComponent.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/DataModule.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/PresenterModule.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/Faq.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/delegates/EventDelegate.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/delegates/contract/IEventDelegate.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/FaqRepository.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/contract/IFAQRepository.java
app/src/main/java/org/fossasia/openevent/app/module/faq/list/FaqListAdapter.java
app/src/main/java/org/fossasia/openevent/app/module/faq/list/FaqListFragment.java
app/src/main/java/org/fossasia/openevent/app/module/faq/list/FaqListPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/faq/list/contract/IFaqListPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/faq/list/contract/IFaqListView.java
app/src/main/java/org/fossasia/openevent/app/module/faq/list/viewholder/FaqViewHolder.java
app/src/main/java/org/fossasia/openevent/app/module/main/MainActivity.java
app/src/main/res/drawable/ic_faq.xml
app/src/main/res/layout/faq_layout.xml
app/src/main/res/layout/faqs_fragment.xml
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/values/strings.xml

Fixes #667 
Changes: Loading FAQ list associated with an event through network, cache it for later use in the database, and load data selectively from network and database.

feat: Added FAQ List for an Event

---

app/src/main/java/org/fossasia/openevent/app/module/event/create/CreateEventFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/create/CreateEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/create/contract/ICreateEventView.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/CreateEventPresenterTest.java

Fixes #613 
Changes: Create Event Activity will finish and send an intent to the fragment that started that activity, which is EventListFragment. (However, EventListFragment's parent activity is MainActivity, thus the intent will first be passed to the MainActivity) EventListFragment will then know that creating the event was successful as its onActivityResult function will be called.
Edit: Now just shows a toast instead.
In this GIF, we create an event named "lol"
@srv-twry @iamareebjamal Could you help me to review this?
However, EventListFragment does not automatically refresh after the event is created. I have tried calling the function `getPresenter().loadUserEvents(true)` inside onActivityResult to try to refresh the events list, but to no avail. Is …

fix: Create Event Activity will finish after event is created

---

app/src/main/java/org/fossasia/openevent/app/module/event/copyright/CreateCopyrightPresenter.java

Fixes #711 
Changes: Empty input fields are made null to prevent HTTP 422 error.

fix: Nullify empty fields in Copyright Form

---

app/src/main/java/org/fossasia/openevent/app/common/app/binding/BindingAdapters.java
app/src/main/res/layout/ticket_create_form.xml
app/src/main/res/values/strings.xml

Fixes #655 
Changes: The user can now add the maximum and minimum values of 

feat: Allow user to fill minOrder maxOrder details (#655)

---

app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/CopyrightRepository.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventFragment.java

Fixes #703 
Changes: Save copyright in db
Use recommended onPrepareOptionsMenu to change menu items
test event4 already has a copyright hence it is displayed correctly and menu item says "Edit copyright"
Test event 5 doesn't have a copyright hence it says "Create Copyright"

fix: Save copyright in db

---

app/src/main/java/org/fossasia/openevent/app/module/attendee/list/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/list/EventListFragment.java
app/src/main/java/org/fossasia/openevent/app/module/faq/list/FaqListFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsFragment.java

Fixes #705 
Changes: Disable the SwipeRefreshLayout's ProgressBar once refresh is activated so that only the bigger ProgressBar (center) is visible while refreshing.

fix: Remove any one of the two progress bars #705

---

app/src/main/java/org/fossasia/openevent/app/common/data/repository/CopyrightRepository.java
app/src/test/java/org/fossasia/openevent/app/unit/model/CopyrightRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/CreateCopyrightPresenterTest.java

Fixes #702 
Changes: Create test for 
1. Copyright Repository
2. CopyrightCreatePresenter
Remove deletion of previous Copyright in CopyrightRepository when fetching copyright.

test: Create tests for Copyright module

---

app/src/main/java/org/fossasia/openevent/app/common/app/di/module/ChangeListenerModule.java
app/src/main/java/org/fossasia/openevent/app/module/faq/list/FaqListPresenter.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/FaqListPresenterTest.java

Fixes #729 
Changes: Database Change Listener used to listen changes in FAQ Database. The UI is updated automatically as an FAQ is created.

fix: Update FAQ List UI automatically on FAQ Creation

---

app/src/main/java/org/fossasia/openevent/app/module/organizer/detail/OrganizerDetailPresenter.java

Fixes #754 
Changes: Removed extra call to onResult in Organizer Detail Presenter.

fix: Fixed Multiple calls to onResult

---

app/src/main/java/org/fossasia/openevent/app/common/app/di/component/AppComponent.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/ChangeListenerModule.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/PresenterModule.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/CopyrightRepository.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/contract/ICopyrightRepository.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/contract/IAboutEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/copyright/update/UpdateCopyrightFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/copyright/update/UpdateCopyrightPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/copyright/update/contract/IUpdateCopyrightPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/copyright/update/contract/IUpdateCopyrightView.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/AboutEventPresenterTest.java

Fixes #737 
Changes: Add feature to update the Copyright of the Event.

feat: Enable Updating Copyright

---

app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventFragment.java
app/src/main/java/org/fossasia/openevent/app/module/organizer/detail/OrganizerDetailFragment.java

Fixes #705 
Changes: Multiple progress bars were removed from the OrganizersDetailFragment and AboutEventFragment.

fix:Multiple Progress bars don't appear on refreshing

---

app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/CopyrightRepository.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/contract/ICopyrightRepository.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/contract/IAboutEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/contract/IAboutEventVew.java
app/src/main/res/menu/menu_about_event.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/unit/presenter/AboutEventPresenterTest.java

Fixes #738 
Changes: Added an option to delete the Copyright of the Event if it exists

feat: Allow deleting Copyright of the Event

---

app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventPresenter.java
app/src/test/java/org/fossasia/openevent/app/unit/model/CopyrightRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/AboutEventPresenterTest.java

Fixes #848 
Changes: Updated tests for ```AboutEventPresenterTest``` and ```CopyrightRepositoryTest```
Modified ```deleteCopyright``` method in the ```AboutEventPresenter``` to allow Unit testing.

test: Update tests for the Copyright module

---

app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/update/IUpdateCopyrightView.java
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/update/UpdateCopyrightFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/update/UpdateCopyrightPresenter.java

Fixes #852 
Changes: Removed static Copyright field from the UpdateCopyrightFragment
Copyright fetched from the database.

fix: Remove static Copyright field from UpdateCopyrightFragment

---

ISSUE_TEMPLATE/bug.md
ISSUE_TEMPLATE/chore.md
ISSUE_TEMPLATE/feature.md
README.md

Fixes #821 
Changes: Separate issue templates can now be used from the README.md

doc: add separate issue template

---

app/src/main/java/org/fossasia/openevent/app/core/event/create/CreateEventActivity.java

Fixes #861 
The app no longer crashes on creating new events.

fix: App doesn't crash on creating new events

---

app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventActivity.java
app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/CreateCopyrightFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/CreateCopyrightPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/ICreateCopyrightView.java
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/update/UpdateCopyrightFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/update/UpdateCopyrightPresenter.java
app/src/main/res/layout/about_event_activity.xml
app/src/main/res/layout/copyright_create_form.xml
app/src/main/res/layout/copyright_create_layout.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/unit/presenter/CreateCopyrightPresenterTest.java

Fixes #712 
Changes: 
1. Changed AboutEventActivity to support all fragments(CreateCopyright, UpdateCopyright) from same about activity fragment container.
2. Added Runtime Validation of fields in CreateCopyrightFragment.
3. Added Validation for Year field on clicking submit. 
4. Changed CreateCopyright Fragment from BaseBottomSheetFragment to BaseFragment.
5. Changed UpdateCopyrightFragment from BaseBottomSheetFragment to BaseFragment.

fix: Runtime Validation in CreateCopyright BaseFragment

---

app/src/main/java/org/fossasia/openevent/app/core/main/MainActivity.java
app/src/main/java/org/fossasia/openevent/app/core/settings/SettingsFragment.java
app/src/main/res/layout/about_event_fragment.xml
app/src/main/res/layout/faqs_fragment.xml
app/src/main/res/layout/fragment_attendees.xml
app/src/main/res/layout/tickets_fragment.xml

Fixes #682 
Changes: 
1. All fragments are now being added to backstack after selection
2. The background colour of SettingsFragment is changed to remove transparency (as it is added over DashboardFragment)
Screenshots of the change:

Add all fragments except dashboard, to backstack

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/data/auth/AuthHolder.java
app/src/test/java/org/fossasia/openevent/app/data/auth/AuthHolderTest.java

- Set private member equal to token
- Use getToken() in getAuthorization()
- Return null from getAuthorization is token is null
- Change logic in Authenticator Interceptor
Fixes #881

fix: Save token in AuthHolder

---

app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventActivity.java
app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/CreateCopyrightFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/update/UpdateCopyrightFragment.java

Fixes #884 
Changes: 
1. Add Copyright Fragment to backstack
2. Change activity's home action to `finish()` only when there's no fragment in backstack
Screenshots of the change:

Fix bug: Pressing back on create/edit copyright exits activity #884

---

app/src/main/java/org/fossasia/openevent/app/core/organizer/detail/OrganizerDetailActivity.java
app/src/main/java/org/fossasia/openevent/app/core/organizer/detail/OrganizerDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/core/organizer/update/UpdateOrganizerInfoFragment.java

Fixes #885 
Changes:
The edit organizer info fragment was added to backstack and the onBackPressed( ) was overridden so that when the count of number of fragment in backstack is greater than one , then the fragment should pop from the backstack and if count is 0 , activity can be exited.

fix: Pressing back pops from backstack

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/ApiModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/ChangeListenerModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/RepoModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/android/MainFragmentBuildersModule.java
app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java
app/src/main/java/org/fossasia/openevent/app/core/session/list/SessionsAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/session/list/SessionsFragment.java
app/src/main/java/org/fossasia/openevent/app/core/session/list/SessionsPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/session/list/SessionsView.java
app/src/main/java/org/fossasia/openevent/app/core/session/list/viewholder/SessionViewHolder.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/viewholder/TracksViewHolder.java
app/src/main/java/org/fossasia/openevent/app/data/db/configuration/OrgaDatabase.java
app/src/main/java/org/fossasia/openevent/app/data/session/Session.java
app/src/main/java/org/fossasia/openevent/app/data/session/SessionApi.java
app/src/main/java/org/fossasia/openevent/app/data/session/SessionRepository.java
app/src/main/java/org/fossasia/openevent/app/data/session/SessionRepositoryImpl.java
app/src/main/java/org/fossasia/openevent/app/data/tracks/Track.java
app/src/main/res/layout/session_layout.xml
app/src/main/res/layout/sessions_fragment.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/core/presenter/SessionsPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/data/repository/SessionRepositoryTest.java

Fixes #902 
Changes: 
1. The user can view list of Sessions associated with event.
2. Save Sessions in database for offline use.
3. Tests are also added.

feat: List of Session for Event

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/ApiModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/ChangeListenerModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/RepoModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/android/MainFragmentBuildersModule.java
app/src/main/java/org/fossasia/openevent/app/core/main/FragmentNavigator.java
app/src/main/java/org/fossasia/openevent/app/core/speaker/list/SpeakersAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/speaker/list/SpeakersFragment.java
app/src/main/java/org/fossasia/openevent/app/core/speaker/list/SpeakersPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/speaker/list/SpeakersView.java
app/src/main/java/org/fossasia/openevent/app/core/speaker/list/viewholder/SpeakerViewHolder.java
app/src/main/java/org/fossasia/openevent/app/data/db/configuration/OrgaDatabase.java
app/src/main/java/org/fossasia/openevent/app/data/speaker/Speaker.java
app/src/main/java/org/fossasia/openevent/app/data/speaker/SpeakerApi.java
app/src/main/java/org/fossasia/openevent/app/data/speaker/SpeakerRepository.java
app/src/main/java/org/fossasia/openevent/app/data/speaker/SpeakerRepositoryImpl.java
app/src/main/res/drawable/ic_people.xml
app/src/main/res/layout/speaker_item.xml
app/src/main/res/layout/speakers_fragment.xml
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/values/strings.xml

Fixes #647 
Changes: 
- Fetch speakers for an event
- Save in the database
- Migrated the database
- Implemented staggered grid layout similar to the one implemented in the open-event-android project.

feat: list speakers under an event

---

app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsFragment.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsListAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsView.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/viewholder/SponsorsViewHolder.java
app/src/main/java/org/fossasia/openevent/app/data/sponsor/SponsorApi.java
app/src/main/java/org/fossasia/openevent/app/data/sponsor/SponsorRepository.java
app/src/main/java/org/fossasia/openevent/app/data/sponsor/SponsorRepositoryImpl.java
app/src/main/res/layout/sponsor_item.xml
app/src/main/res/values/strings.xml

Fixes #939 
Changes: 
Adds a delete icon to sponsor item, which deletes the Sponsor item from the server and the local database upon confirmation

feat: Add implementation for Sponsor deletion #939

---

app/src/main/java/org/fossasia/openevent/app/ui/views/AbstractDateTimePicker.java
app/src/main/java/org/fossasia/openevent/app/ui/views/DatePicker.java
app/src/main/java/org/fossasia/openevent/app/ui/views/OnDateTimeChangedListener.java
app/src/main/java/org/fossasia/openevent/app/ui/views/TimePicker.java

Fixes #946 
Changes: Extracted out the common code in an ```AbstractDateTimePicker``` class.
Extracted out the ```DateTimeChangeListener``` to a different file

fix: Polish custom Date and Time pickers by extracting common code

---

app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsFragment.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsListAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsView.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/viewholder/SponsorsViewHolder.java
app/src/main/java/org/fossasia/openevent/app/data/sponsor/Sponsor.java
app/src/main/res/layout/sponsor_item.xml
app/src/main/res/menu/menu_sponsors.xml

Fixes #957 
Changes: 
1. moves edit and delete options from every item in the list to the toolbar 
2. allows the user to long press an item to edit or delete it
3. supports multiple deletions
4. removes edit option in case of multiple selections
5. re-clicking the last selected item unselects
6. re-clicking the only selected item resets the toolbar
**Gif for the change:**
**Delete Operation:**
**Edit operation:**

feat: Move edit and delete options to toolbar #957

---

app/src/main/java/org/fossasia/openevent/app/core/auth/SharedViewModel.java
app/src/main/java/org/fossasia/openevent/app/core/auth/forgot/request/ForgotPasswordFragment.java
app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java
app/src/main/java/org/fossasia/openevent/app/core/auth/signup/SignUpFragment.java

Fixes #979 
Changes: 
1. Typed emails now persist between different screen changes so that the user doesn't need to retype email repeatedly.
Gif for the change:

Make typed email persist between different AuthActivity fragments

---

app/src/main/res/layout/sponsor_item.xml

Fixes #1008 .
Changes: Set `ic_photo_shutter.xml` as the placeholder image for Sponsor.

feat: Set placeholder image for Sponsor

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/ChangeListenerModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/ViewModelModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/android/ActivityBuildersModule.java
app/src/main/java/org/fossasia/openevent/app/common/mvp/view/BaseBottomSheetFragment.java
app/src/main/java/org/fossasia/openevent/app/core/main/MainActivity.java
app/src/main/java/org/fossasia/openevent/app/core/speakerscall/create/CreateSpeakersCallFragment.java
app/src/main/java/org/fossasia/openevent/app/core/speakerscall/create/CreateSpeakersCallView.java
app/src/main/java/org/fossasia/openevent/app/core/speakerscall/create/CreateSpeakersCallViewModel.java
app/src/main/java/org/fossasia/openevent/app/core/speakerscall/detail/SpeakersCallFragment.java
app/src/main/java/org/fossasia/openevent/app/core/speakerscall/detail/SpeakersCallPresenter.java
app/src/main/java/org/fossasia/openevent/app/data/speakerscall/SpeakersCallApi.java
app/src/main/java/org/fossasia/openevent/app/data/speakerscall/SpeakersCallRepository.java
app/src/main/java/org/fossasia/openevent/app/data/speakerscall/SpeakersCallRepositoryImpl.java
app/src/main/res/layout/speakers_call_create_form.xml
app/src/main/res/layout/speakers_call_create_layout.xml
app/src/main/res/layout/speakers_call_fragment.xml
app/src/main/res/values/strings.xml

Fixes #1029 
Changes: 
1. Organizer can create speakers call for event if it does not already exist.
2. Database change listener reflects result in UI without explicitly refreshing.

feat: Create Call for Speakers

---

app/src/main/java/org/fossasia/openevent/app/core/share/ShareEventFragment.java

Fixes #1066 
Changes: The Share fragment now shows "Share" as the toolbar title.

chore: Changed the Share fragment title

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/android/MainFragmentBuildersModule.java
app/src/main/java/org/fossasia/openevent/app/common/mvp/view/BaseDialogFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/EventListFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/EventsListAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/EventsPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/EventsView.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/SalesSummaryFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/SalesSummaryPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/SalesSummaryView.java
app/src/main/res/layout/event_layout.xml
app/src/main/res/layout/fragment_sales_summary.xml
app/src/main/res/layout/ticket_analytics.xml
app/src/main/res/layout/ticket_analytics_item.xml

Fixes #1059 
Changes:
1. Long pressing Event List items shows tickets sold summary
2. Similar layout has replaced the older horizontal view for Dashboard.

Open tickets-sold summary on long pressing Event list item

---

app/src/main/res/layout/share_event_layout.xml

Fixes #1075 
Changes: The placeholder in the Share Fragment now shows the event image (if it was set earlier).

bug: Event image visible in placeholder

---

app/src/main/java/org/fossasia/openevent/app/core/session/create/CreateSessionFragment.java
app/src/main/java/org/fossasia/openevent/app/core/session/create/CreateSessionPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/session/create/CreateSessionView.java

Fixes #1077 
Changes: 
1. Closing session layout on creation.
2. Closing session layout on update.

fix: Close Session layout on creation

---

app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

Fixes #1074 
Changes: Adds Device name preference to Settings
(An extra screen for Device name exists in EventBrite. Please suggest if it needs to be added in Orga App also.)

feat: Add Device Name preference to Settings

---

app/src/main/java/org/fossasia/openevent/app/common/Constants.java
app/src/main/java/org/fossasia/openevent/app/core/event/create/CreateEventFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/create/CreateEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/event/create/CreateEventView.java
app/src/main/java/org/fossasia/openevent/app/core/main/FragmentNavigator.java
app/src/main/java/org/fossasia/openevent/app/core/settings/EventSettingsFragment.java
app/src/main/java/org/fossasia/openevent/app/core/settings/PaymentPrefsFragment.java
app/src/main/java/org/fossasia/openevent/app/data/Preferences.java
app/src/main/java/org/fossasia/openevent/app/data/SharedPreferencesImpl.java
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/event_preferences.xml
app/src/main/res/xml/payment_preferences.xml
app/src/test/java/org/fossasia/openevent/app/core/presenter/CreateEventPresenterTest.java

Fixes #1049 
Changes: Adds Event Settings -> Payment Preferences
Gif for the change:

Add Event Payment preferences

---

app/src/main/java/org/fossasia/openevent/app/core/sponsor/create/CreateSponsorPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/update/UpdateSponsorPresenter.java

Fixes #1078 
Changes: 
1. Set Empty fields while Sponsors creation to null.
2. Set Empty fields while Sponsors update to null.

fix: Nullify Empty Fields in Sponsors

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/ViewModelModule.java
app/src/main/java/org/fossasia/openevent/app/common/livedata/SingleEventLiveData.java
app/src/main/java/org/fossasia/openevent/app/core/main/EventViewModel.java
app/src/main/java/org/fossasia/openevent/app/core/main/MainActivity.java
app/src/main/java/org/fossasia/openevent/app/core/main/MainPresenter.java
app/src/test/java/org/fossasia/openevent/app/core/presenter/MainPresenterTest.java

Fixes #1122
Checklist:
Changes: 
- Add EventViewModel extracting related code from MainPresenter
- Adds an ActionLiveData in order to send one time action from ViewModel to View.(Reference: Google MVVM samples)
- As a consequence, the dashboard no longer overrides the fragments.
**Note**
Tests will be added in a separate PR as this PR was getting huge. One more PR is needed in order to completely remove the MainPresenter. Tests will be added along with that PR.

feat: Add EventViewModel extracting related code from MainPresenter

---

app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java

Fixes #836 
Checklist:
Changes: Change VmPolicy to `penaltyLog`. ThreadPolicy isn't causing any issues right now hence left it untouched. Note that `penaltyDialog` is only available with ThreadPolicy.

chore: Set VmPolicy to penaltyLog

---

app/src/main/java/org/fossasia/openevent/app/core/main/EventViewModel.java

Fixes #589 
Checklist:
Changes: Run onStart only once in the EventViewModel and as a result stop dashboard from overriding the fragments.

fix: Run onStart only once in EventViewModel

---

app/proguard-rules.pro

Fixes #1196 
Checklist:
Changes: Updated proguard rules file.

chore: Update proguard rules file

---

app/src/main/java/org/fossasia/openevent/app/core/event/list/EventListFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/pager/ListPageFragment.java

Fixes #1198 
Checklist:
Changes: Correct place for instantiation of options menu, thus fixing persisting events list menu

fix: hide events list menu on fragment change

---

app/src/main/java/org/fossasia/openevent/app/core/main/MainActivity.java

Fixes #1203 
Checklist:
Changes: Handles back press when no event is selected.

fix: empty dashboard on back presses with no selected event

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/ViewModelModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/android/MainFragmentBuildersModule.java
app/src/main/java/org/fossasia/openevent/app/core/main/FragmentNavigator.java
app/src/main/java/org/fossasia/openevent/app/core/settings/EventSettingsFragment.java
app/src/main/java/org/fossasia/openevent/app/core/settings/restriction/CheckInRestrictionView.java
app/src/main/java/org/fossasia/openevent/app/core/settings/restriction/CheckInRestrictions.java
app/src/main/java/org/fossasia/openevent/app/core/settings/restriction/CheckInRestrictionsAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/settings/restriction/RestrictionsViewHolder.java
app/src/main/java/org/fossasia/openevent/app/core/settings/restriction/TicketSettingsViewModel.java
app/src/main/java/org/fossasia/openevent/app/data/ticket/Ticket.java
app/src/main/java/org/fossasia/openevent/app/data/ticket/TicketApi.java
app/src/main/java/org/fossasia/openevent/app/data/ticket/TicketRepository.java
app/src/main/java/org/fossasia/openevent/app/data/ticket/TicketRepositoryImpl.java
app/src/main/res/layout/ticket_setting_layout.xml
app/src/main/res/layout/ticket_settings_fragment.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/event_preferences.xml

Fixes #973 
Changes: Adds check-in restrictions preferences for each ticket in Settings
GIF:

feat: Add check-in restrictions in settings

---

app/build.gradle

Fixes #1302 
Checklist:
Changes: 

fix: Capitalize App Name

---

app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailActivity.java
app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java
app/src/main/java/com/eventyay/organizer/core/organizer/update/UpdateOrganizerInfoFragment.java
app/src/main/java/com/eventyay/organizer/core/organizer/update/UpdateOrganizerInfoView.java

Fixes #1334 
Checklist:
Changes: Adds confirmation when exiting UpdateOrganizerInfo Fragment

feat: Confirm dialog on exiting Update Organizer Info

---

README.md

Chore: Update Play store and F-Droid links in README.md

---

app/src/main/java/com/eventyay/organizer/OrgaApplication.java

Fixes #1356 
After reading through some articles, I have found out that using strict policy on certain devices will cause a DiskReadViolation that may not be related to the app's code, but due to an external library or each hardware maker's specific software.
By outting " .permitDiskReads()" we can avert this situation. In the comment there is a link to an article where this is explained in detail.
Checklist:
Changes: [Add here what changes were made in this issue and if possible provide links.]

Issue App crashing on Opening in Android Oreo 8.1 #1356

---

app/src/main/java/com/eventyay/organizer/core/auth/signup/SignUpFragment.java

Fixes #1391 
Checklist:
Changes: 
Now the invalid field message will disappear when the user corrects the length of the password and then clicks on some other field.
Screenshots:

fix: Invalidate invalid field message on text changes

---

app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardFragment.java
app/src/main/res/values/strings.xml

Fixes #1419 
Checklist:
Changes: 
Now the share button appears on the right side in the dialog box and a not now button has been added which closes the dialog.

fix: Move Share button to the right and add 'Not now' button

---

app/src/main/java/com/eventyay/organizer/core/main/FragmentNavigator.java
app/src/main/java/com/eventyay/organizer/core/main/MainActivity.java
app/src/test/java/com/eventyay/organizer/core/main/FragmentNavigatorTest.java

Fixes #1383 
Checklist:
Note: This bug was not afflicting only the Attendees fragment having the Activity Log as a subfragment but, every other fragment having subfragments.
Changes: Correct menu item is selected in Navigation drawer even when the back button is pressed from a subfragment.
Screenshot after the change:

fix: Correct selection of menu item in Navigation drawer

---

app/src/main/res/layout/sign_up_fragment.xml

Fixes #1374 
Checklist:
Changes: Removed the user.password field from confirm password edit text, which populated the confirm password edit text when the device screen was rotated. 
Explanation : When the user entered the password, the password was stored in an object of the User class. When the screen was rotated, the confirm password edit text referred the same field, which caused that field to get filled with the same password that was entered by the user in the password field. 
Previous behaviour:
Current behaviour:

fix: Confirm password filling automatically on device rotation

---

app/src/main/java/com/eventyay/organizer/core/sponsor/create/CreateSponsorFragment.java
app/src/main/java/com/eventyay/organizer/ui/ViewUtils.java

Fixes #1430 
Checklist:
Changes: Sponsor Name field will have focus and keyboard will open when Create Sponsor fragment is opened.

fix: focus on sponsor name and show keyboard when create spononsor fragment is opened

---

app/src/main/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java

Fixes #1441  
Checklist:
Changes: 
Upload Image option now gets trigger when we tap on the imageview of Update event and not from anywhere else in the layout.

Fixed #1441  Edit event triggers to upload image from anywhere in the layout of edit event

---

app/src/main/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java
app/src/main/res/layout/event_create_form.xml

Fixes #1458 
Checklist:
Changes: 
Now, image upload will trigger even when the user clicks outside the camera icon in UpdateEventFragment.

fix: Trigger image upload in Update Event on clicking anywhere in the ImageView

---

app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesFragment.java

Fixes #1465 
Checklist:
Changes: 
Now, the FAB would not appear on scrolling if the list of attendees is empty.

fix: Prevent Scan QR FAB from showing on empty attendees list

---

app/src/main/java/com/eventyay/organizer/core/faq/create/CreateFaqFragment.java

Fixes #1468 
Checklist:
Changes: 
After this change, submission will display error if user enters just spaces without any text in the question and answer fields of Create FAQ.

fix: Validate Create FAQ question and answer fields for just spaces without text

---

app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java
app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailPresenter.java
app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailView.java
app/src/main/java/com/eventyay/organizer/data/auth/AuthApi.java
app/src/main/java/com/eventyay/organizer/data/auth/AuthService.java
app/src/main/java/com/eventyay/organizer/data/auth/AuthServiceImpl.java
app/src/main/java/com/eventyay/organizer/data/auth/model/ResendVerificationMail.java
app/src/main/java/com/eventyay/organizer/data/auth/model/ResendVerificationMailResponse.java
app/src/main/res/layout/organizer_detail_layout.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/eventyay/organizer/core/presenter/OrganizerDetailPresenterTest.java

Fixes #1472 
Checklist:
Changes: 
Now, the user would have the option to trigger resending of verification mail for an unverified account.

feat: Option to resend verification mail

---

app/src/main/java/com/eventyay/organizer/core/track/create/CreateTrackFragment.java

fix: focus on track name and show keyboard when create track fragment is opened

---

app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListPresenter.java

Fixes #1474 
Checklist:
Changes: 
Now, FAQ list would auto-update when any item is deleted.

fix: Update FAQ list automatically on item deletion

---

app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventViewModel.java
app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThree.java
app/src/main/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java

Fixes #1486 
Checklist:
Changes: 
Now, "Network Not Available" message would be displayed when the user tries to edit event but internet connection is not available.

 fix: Display unavailability of network connection during event update

---

app/src/main/res/layout/event_create_form.xml

Fixes #1510 
Checklist:
Changes: 
Now, the correct state radio button would remain checked in Edit Event.

fix: Check correct event state radio button in Edit Event

---

app/src/main/java/com/eventyay/organizer/core/event/list/EventsViewModel.java

Fixes #1493 App crashes on sorting events list when list is empty 
Checklist:
Changes: 
Added a null check in sortBy function

fix: Add null check before sorting events

---

app/src/main/res/layout/update_organizer_form.xml

Fixes #1525 
Checklist:
Changes: 
Provided bottom margin for the Google Plus field so that it does not hide behind the 'Done' button.

fix: Make Google Plus field accessible in update organizer form

---

app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventViewModel.java

Fixes #1584 
Checklist:
Changes: 
Added verification for the case when start time is before current time which would be verified during the first step of event creation along with proper error message.
Also removed an unused import.

fix: Show wrong start time error after first step itself

---

app/src/main/java/com/eventyay/organizer/utils/ErrorUtils.java

Fixes #1589 
Checklist:
Changes: 
Added condition `if (throwable instanceof HttpException)`

fix: Prevent ClassCastException in ErrorUtils

---

app/src/main/java/com/eventyay/organizer/data/event/EventStatistics.java
app/src/main/java/com/eventyay/organizer/data/event/SpeakerStatistics.java
app/src/main/res/layout/event_statistics.xml

**Fixes** #1586 
**Checklist**
**Changes**
Creates another class for speaker statistics to incorporate the sub-fields of the speakers object.
Hence fixes the `JsonMappingException: Can not deserialize instance of java.lang.Long out of START_OBJECT token` on loading the event dashboard.

fix: Create SpeakerStatistics

---

app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventActivity.java

Fixes #1638 
Checklist:
Changes: 
Now, alert dialog would appear whenever the dialog is not there on the screen and the back button is pressed.
GIF:

fix: Prevent closing of Edit Event without confirmation dialog

---

app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesFragment.java
app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesPresenter.java
app/src/main/java/com/eventyay/organizer/core/attendee/list/SwipeController.java

Fixes #1646 
Checklist:
Changes:
Now, updated and complete list of attendees loaded till then would be used in SwipeController.

fix: Prevent crash at check-in on second page onwards

---

app/src/main/java/com/eventyay/organizer/ui/views/AbstractDateTimePicker.java

Fix: DatePicker and TimePicker doesn't display time chosen before when clicked
Fixes #1548 
Changes: 
I change the use of ZonedDateTime by the currentTime chosen before so that whenever we click on TimePicker or DatePicker, it shows the current time and date chosen

fix: DatePicker and TimePicker doesn't display time chosen before when clicked

---

app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesFragment.java
app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesPresenter.java
app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesView.java
app/src/main/java/com/eventyay/organizer/data/attendee/AttendeeRepositoryImpl.java
app/src/playStore/java/com/eventyay/organizer/core/attendee/qrscan/ScanQRPresenter.java

Fixes #1672 
Checklist:
Changes: 
- Proper attendee IDs are being set.
- Attendee check-in status gets updated after scanning.

fix: Update check-in system to work properly

---

app/build.gradle

Updated version code to `10` and version name to `1.2.0`.

chore: Bump version code and name for release of v1.2.0

---

app/src/main/java/com/eventyay/organizer/core/role/invite/RoleInviteFragment.java
app/src/main/java/com/eventyay/organizer/core/role/invite/RoleInviteViewModel.java

chore: Dismiss RoleInviteFragment after invitation is sent

---

app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardFragment.java
app/src/main/res/layout/event_statistics.xml
app/src/main/res/layout/order_statistics.xml

Fixes #1574  
Checklist:
Changes: 
State of Event Statistics switch and Order Statistics switch would now be retained on screen rotation.

fix: Retain state of statistics switches on screen rotation

---

app/src/main/res/menu/activity_main_drawer.xml

Fixes #1748 
Changes: 
Shifted 'My Events' to the first position in navigation drawer.

chore: Move 'My Events' to the first position in navigation drawer

---

app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardFragment.java
app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardPresenter.java
app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardView.java
app/src/main/res/layout/fragment_event_details.xml
app/src/test/java/com/eventyay/organizer/core/presenter/EventDashboardPresenterTest.java

Fixes #1761 
**Changes:** 
Added a box above the section of 'Gross Sales' in Event Dashboard, containing the following items:
- Check In
- Orders
- Tickets
- Edit Event
- Event Settings
Removed these items from the navigation drawer.
Orders, Tickets and Edit Event would show only in Developer Mode.
**Screenshot for the change:**

feat: Provide access to features via Event Dashboard

---

scripts/update-apk.sh

chore: Update APK naming convention

---

app/build.gradle
app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesFragment.java
app/src/main/java/com/eventyay/organizer/core/attendee/list/listeners/AttendeeItemCheckInEvent.java
app/src/main/java/com/eventyay/organizer/data/attendee/Attendee.java
app/src/main/java/com/eventyay/organizer/data/attendee/AttendeeDelegateImpl.java

chore: Bump FastAdapter version and fix errors

---

app/src/main/java/com/eventyay/organizer/utils/ErrorUtils.java

Fixes #1833 
Changes:
Now, error `HTTP 409 CONFLICT` would be handled properly and proper error message would be shown.

chore: Show proper error message for 409 error code

---

app/build.gradle

Updated version code to `15` and version name to `1.5.0`.

chore: Bump version name and code for v1.5.0

---

app/src/main/res/layout/main_nav_header.xml
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/values/strings.xml

Fixes #1847 
Changes:
Now, event end date and time would also be shown in navigation drawer and changed `My Account` to `Account`.

chore: Show end time in nav drawer and change title of account option

---

app/src/main/java/com/eventyay/organizer/core/notification/list/NotificationsAdapter.java

Fixes #1868 
Changes: 
Now, HTML tags would not be present in notification messages.

chore: Strip HTML tags from notifications

---

app/build.gradle

Updated version code to `16` and version name to `1.6.0`.

chore: Bump version code and name for v1.6.0

---

app/src/main/java/com/eventyay/organizer/core/settings/LegalPreferenceFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/legal_preferences.xml

Fixes #1890 
Changes:
- Used correct links for Privacy Policy and Terms of Service.
- Changed 'Cookie Policy' to 'Refund Policy'.

fix: Use correct policy links and change Cookie Policy to Refund Policy

---

app/src/main/java/com/eventyay/organizer/core/auth/login/LoginViewModel.java

chore: Display user friendly error message for wrong credentials
