.bowerrc
.editorconfig
.gitignore
.travis.yml
bower.json
config.xml
gulpfile.js
hooks/after_prepare/010_add_platform_class.js
ionic.config.json
package.json
www/css/ionic.app.css
www/index.html
www/js/app.js
www/js/controllers.js
www/js/directives.js
www/js/routes.js
www/js/services.js

Added comments in certain places which would allow collaborators to better understand how to add pages and implement controllers.
@mariobehling please review and merge

Added helper comments and code style enforced

---

.gitignore
.travis.yml
README.md
gulpfile.js
package.json
www/index.html
www/js/app.js
www/js/config.js
www/js/controllers.js
www/js/directives.js
www/js/routes.js
www/js/services.js
www/templates/login.html

Resolves #6.
@mariobehling please review and merge.
---
**Sample android application built from current source:** [android-debug.zip](https://github.com/fossasia/open-event-orga-app/files/432743/android-debug.zip)

Added Login functionality

---

README.md

Fixed incorrect link in README (thanks to @the-dagger for pointing out) and added technologies to the technology stack
@mariobehling please review and merge.

Fixed incorrect link in README and added technologies to the technology stack

---

README.md

Resolves #14.
@mariobehling please review and merge.

Added Node.js installation guidelines to the README

---

gulpfile.js
scss/ionic.app.scss
www/js/controllers/events/attendees_controller.js
www/js/routes.js
www/scss/app.scss
www/templates/event/attendees.html
www/templates/event/dashboard.html

Partially resolves #9.
@mariobehling please review and merge

Attendees List with Search

---

.travis.yml

Fixes #22 @niranjan94 Please review and merge

Remove unnecessary dependencies

---

app/pages/event-attendees/event-attendees.html
app/pages/event-attendees/event-attendees.ts
app/pages/event-dashboard/event-dashboard.html
app/pages/event-dashboard/event-dashboard.ts
app/pages/events/events.html
app/pages/events/events.ts
app/pages/login/login.html
config.xml

Resolves #5.
@mariobehling please review and merge

Check in attendees with QR Code

---

src/interfaces/attendee.queue.ts
src/pages/event-attendees/event-attendees.ts
src/services/queue.service.ts

Can be merged as soon as https://github.com/fossasia/open-event-orga-server/pull/3302 is merged.

Change QR Code and Attendee Identifier format

---

src/pages/event-dashboard/event-dashboard.ts

Fixes #42 _Total tickets_ value was being incremented in place of _attendees present_. The same is corrected.

Event dashboard values display corrected

---

src/pages/event-attendees/event-attendees.ts

Match case search removed

---

src/app/app.component.ts

Two alert dialogs issue solved

---

src/pages/login/login.html

Fixes #45: Android Standard "Go" button not working for login
Changes done: Made the UI a form. A submit is initiated on "Go" press or by clicking the login button which fires the login() method.

fix: Made Android Go button working for login

---

src/pages/login/login.html
src/pages/login/login.ts

**Fixes issue**: #44 Only show email and password and a checkbox for server on start screen.
**Changes Done:** 
-  Added a checkbox for choosing server **eventyay.com**
-  If unchecked, user can mention server manually.
**Relevant Screenshots:**

Fixes #44: Only Show checkbox for selecting server.

---

src/pages/event-attendees/event-attendees.html

Search bar is placed in the toolbar

---

src/pages/event-attendees/event-attendees.html
src/pages/event-attendees/event-attendees.ts
src/pages/event-dashboard/event-dashboard.html
src/pages/event-dashboard/event-dashboard.ts
src/pages/events/events.html
src/pages/events/events.ts

Implemented pull to refresh feature

---

src/pages/events/events.ts

Loaded Event List remains on the screen while Pull Refresh

---

src/pages/events/events.ts

A Network Alert Dialog on Events Page if no network connection

---

src/pages/event-attendees/event-attendees.html

Scan button is fixed at bottom

---

src/pages/event-attendees/event-attendees.html
src/pages/event-attendees/event-attendees.ts

Check In and Checked In Buttons with Confirm Alert on Attendees Page

---

src/pages/event-attendees/event-attendees.html
src/pages/event-attendees/event-attendees.ts
src/pages/event-dashboard/event-dashboard.html
src/pages/event-dashboard/event-dashboard.ts
src/pages/events/events.html

**Fixes: #70**
**Changes Done**
- Load the first spinner only when page loads for first time.
- Changed the refreshing spinner to Material Design single stroke spinner.
**Relevant Screenshots**

Fixed 2 spinners appearing on pages

---

src/pages/event-attendees/event-attendees.ts

QR code validation extended to check if checked in already and valid attendee

---

src/pages/event-dashboard/event-dashboard.html

Check In button overlapping removed on Dashboard

---

src/pages/event-dashboard/event-dashboard.html

Check In button fixed at bottom on Dashboard Page

---

src/pages/event-attendees/event-attendees.ts
src/pages/event-dashboard/event-dashboard.ts

first time spinner stopped in no network scenario

---

src/pages/event-attendees/event-attendees.ts

Confirm Alert to Bar Code Scan Check In

---

.travis.yml
README.md
package.json
src/app/app.module.ts
src/pages/event-attendees/event-attendees.ts
src/pages/event-dashboard/event-dashboard.ts
src/pages/events/events.ts
src/pages/login/login.ts
src/pipes/keys.pipe.ts
src/services/login.service.ts
src/services/network-check.service.ts
tslint.json

upgrade to Ionic version 3.0

---

.travis.yml
app/build.gradle
app/src/main/java/org/fossasia/openevent/app/Adapters/AttendeeListAdapter.java
app/src/main/java/org/fossasia/openevent/app/Adapters/EventListAdapter.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

Fixes #88
- Fixes dependency versions
- Fixes install orderings
- Fixes lint issues
- Logs the output of tests and lint on travis console

fix: Update .travis.yml to fix apk build

---

scripts/update-apk.sh

Fixes #94 
- Copy correct apk to build environment and upload

fix: Auto update apk branch on each travis build

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/adapters/AttendeeListAdapter.java
app/src/main/java/org/fossasia/openevent/app/adapters/EventListAdapter.java
app/src/main/java/org/fossasia/openevent/app/views/AttendeeListActivity.java
app/src/main/java/org/fossasia/openevent/app/views/EventDetailsActivity.java
app/src/main/java/org/fossasia/openevent/app/views/EventsActivity.java
app/src/main/java/org/fossasia/openevent/app/views/LoginActivity.java
app/src/main/java/org/fossasia/openevent/app/views/ScanQRActivity.java

Fixes #97 
- Add butterknife for view injection

feat: Use butterknife for view injection

---

app/src/main/java/org/fossasia/openevent/app/ui/activity/LoginActivity.java

Add butterknife to remaining LoginActivity

feat: Add butterknife to remaining activity

---

app/src/main/java/org/fossasia/openevent/app/contract/model/ICacheModel.java
app/src/main/java/org/fossasia/openevent/app/contract/model/IEventModel.java
app/src/main/java/org/fossasia/openevent/app/contract/model/ILoginModel.java
app/src/main/java/org/fossasia/openevent/app/contract/model/IUtilModel.java
app/src/main/java/org/fossasia/openevent/app/contract/presenter/IEventListPresenter.java
app/src/main/java/org/fossasia/openevent/app/contract/presenter/ILoginPresenter.java
app/src/main/java/org/fossasia/openevent/app/contract/view/IEventListView.java
app/src/main/java/org/fossasia/openevent/app/contract/view/ILoginView.java
app/src/main/java/org/fossasia/openevent/app/data/AndroidUtilModel.java
app/src/main/java/org/fossasia/openevent/app/data/cache/ObjectCache.java
app/src/main/java/org/fossasia/openevent/app/data/network/api/RetrofitEventModel.java
app/src/main/java/org/fossasia/openevent/app/data/network/api/RetrofitLoginModel.java
app/src/main/java/org/fossasia/openevent/app/ui/activity/EventsActivity.java
app/src/main/java/org/fossasia/openevent/app/ui/activity/LoginActivity.java
app/src/main/java/org/fossasia/openevent/app/ui/presenter/EventsActivityPresenter.java
app/src/main/java/org/fossasia/openevent/app/ui/presenter/LoginActivityPresenter.java
app/src/test/java/org/fossasia/openevent/app/EventActivityPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/LoginActivityPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/RetrofitEventModelTest.java
app/src/test/java/org/fossasia/openevent/app/RetrofitLoginModelTest.java

Interfaces renamed to follow I-convention

---

app/src/main/java/org/fossasia/openevent/app/contract/presenter/IEventListPresenter.java
app/src/main/java/org/fossasia/openevent/app/contract/view/IEventListView.java
app/src/main/java/org/fossasia/openevent/app/data/models/User.java
app/src/main/java/org/fossasia/openevent/app/data/models/UserDetail.java
app/src/main/java/org/fossasia/openevent/app/ui/activity/EventsActivity.java
app/src/main/java/org/fossasia/openevent/app/ui/presenter/EventsActivityPresenter.java
app/src/main/java/org/fossasia/openevent/app/utils/Utils.java
app/src/main/res/layout/activity_events.xml
app/src/test/java/org/fossasia/openevent/app/EventActivityPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/UtilsTest.java

Fixes #100 
- Add logged in user's name in EventsActivity
- Add related tests

feat: Add logged in username and more tests

---

app/src/main/java/org/fossasia/openevent/app/contract/model/ICacheModel.java
app/src/main/java/org/fossasia/openevent/app/data/cache/ObjectCache.java
app/src/test/java/org/fossasia/openevent/app/CacheTest.java

- Add `getSize` in cache
- Add more tests for size and duplicate check

test: Add more feature and test in Cache model

---

app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailActivityPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailsActivity.java
app/src/main/java/org/fossasia/openevent/app/event/detail/contract/IEventDetailView.java
app/src/main/res/layout/activity_event_details.xml

Fixes #118 
- Fix variable names and floating point operations

fix: Show correct analytics

---

app/src/main/java/org/fossasia/openevent/app/data/models/Attendee.java
app/src/main/java/org/fossasia/openevent/app/data/models/Ticket.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailActivityPresenter.java
app/src/test/java/org/fossasia/openevent/app/model/EventDataRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java

Fixes #121 
- Complete all cases of tests for Event and Attendee Repository, Presenter and Model

test: Add remaining tests for Event and Attendee model and presenter

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java
app/src/main/java/org/fossasia/openevent/app/data/UtilModel.java
app/src/main/java/org/fossasia/openevent/app/data/contract/ILoginModel.java
app/src/main/java/org/fossasia/openevent/app/data/contract/IUtilModel.java
app/src/main/java/org/fossasia/openevent/app/events/EventsActivity.java
app/src/main/java/org/fossasia/openevent/app/events/EventsPresenter.java
app/src/main/java/org/fossasia/openevent/app/login/LoginActivity.java
app/src/main/java/org/fossasia/openevent/app/login/LoginPresenter.java
app/src/main/java/org/fossasia/openevent/app/utils/JWTUtils.java
app/src/test/java/org/fossasia/openevent/app/model/LoginModelTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventsPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/LoginPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/utils/JWTUtilsTest.java

- Implement JWT expiry parsing
- Add key expiry check
- Add tests for both

feat: Implement login invalidation

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java

Fixes #133 
- Add OrgaApplication `Application` class
- Add on debug on any VM or Thread Policy error -> die strict mode

feat: Add strict mode to application

---

scripts/update-apk.sh

Fix travis upload of built apks

fix: Travis build and test apk upload

---

.travis.yml

fix: Travis cache directory fixed

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java
app/src/main/java/org/fossasia/openevent/app/event/EventContainerActivity.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailsFragment.java
app/src/main/java/org/fossasia/openevent/app/events/EventsActivity.java
app/src/main/java/org/fossasia/openevent/app/login/LoginActivity.java
app/src/main/java/org/fossasia/openevent/app/qrscan/ScanQRActivity.java
app/src/main/java/org/fossasia/openevent/app/utils/Constants.java

Fixes #130 
- Add timber
- Remove `Log` statements
- Remove unused constants
- Remove TODO tags after renaming variables

feat: Add timber and clean up

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java
app/src/main/java/org/fossasia/openevent/app/common/BaseFragment.java
app/src/main/java/org/fossasia/openevent/app/event/EventContainerFragment.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailsFragment.java

feat: Add and configure LeakCanary (#129)

---

app/src/main/java/org/fossasia/openevent/app/data/models/Order.java
app/src/main/java/org/fossasia/openevent/app/qrscan/ScanQRActivity.java
app/src/main/java/org/fossasia/openevent/app/qrscan/ScanQRPresenter.java
app/src/main/java/org/fossasia/openevent/app/qrscan/contract/IScanQRPresenter.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventsPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/ScanQRPresenterTest.java

- Add tests for unit functions, data flow and view integrations
- Fix failing tests by checks and appropriate calls
- Change contract to make QR Presenter more testable
Fixes #139

feat: Add tests for QR Scan Presenter

---

app/src/main/java/org/fossasia/openevent/app/qrscan/ScanQRActivity.java

Locks screen orientation on qr scan activity

---

app/build.gradle
app/src/main/res/layout/fragment_event_details.xml

fixes #157 
**P.S.** I have used hardcode dimension values because that will be taken up as a separate issue #163  with current hardcoded dimensions modification which is required.

Event detail UI modification

---

app/src/main/java/org/fossasia/openevent/app/common/binding/BindingAdapters.java

Adds placeholder image icon in event item

---

app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/attendee_layout.xml
app/src/main/res/layout/event_layout.xml
app/src/main/res/layout/fragment_attendees.xml
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/values-w820dp/dimens.xml
app/src/main/res/values/dimens.xml

modifies @dimens

---

app/src/main/res/layout/fragment_event_details.xml

Moves progress bar on top of the content event detail layout

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java
app/src/main/java/org/fossasia/openevent/app/common/di/component/AppComponent.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/DataModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/DatabaseModule.java
app/src/main/java/org/fossasia/openevent/app/data/EventRepository.java
app/src/main/java/org/fossasia/openevent/app/data/contract/IEventRepository.java
app/src/main/java/org/fossasia/openevent/app/data/db/DatabaseRepository.java
app/src/main/java/org/fossasia/openevent/app/data/db/configuration/DbFlowExclusionStrategy.java
app/src/main/java/org/fossasia/openevent/app/data/db/configuration/OrgaDatabase.java
app/src/main/java/org/fossasia/openevent/app/data/db/contract/IDatabaseRepository.java
app/src/main/java/org/fossasia/openevent/app/data/models/CallForPapers.java
app/src/main/java/org/fossasia/openevent/app/data/models/Copyright.java
app/src/main/java/org/fossasia/openevent/app/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/data/models/License.java
app/src/main/java/org/fossasia/openevent/app/data/models/SimpleModel.java
app/src/main/java/org/fossasia/openevent/app/data/models/SocialLink.java
app/src/main/java/org/fossasia/openevent/app/data/models/Ticket.java
app/src/main/java/org/fossasia/openevent/app/data/models/Version.java
app/src/main/java/org/fossasia/openevent/app/data/network/NetworkService.java
app/src/main/java/org/fossasia/openevent/app/events/EventsPresenter.java
app/src/test/java/org/fossasia/openevent/app/TestOrgaApplication.java
app/src/test/java/org/fossasia/openevent/app/db/SimpleModelTest.java
app/src/test/java/org/fossasia/openevent/app/db/config/BaseUnitTest.java
app/src/test/java/org/fossasia/openevent/app/db/config/DatabaseTestRule.java
app/src/test/java/org/fossasia/openevent/app/model/EventRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventsPresenterTest.java
build.gradle

Fixes part of #156
- Add DbFlow
- Add stetho
- Implement unit tested persistence API for loading evemt

feat: Add data persistence via DBFlow

---

app/src/main/java/org/fossasia/openevent/app/data/EventRepository.java
app/src/main/java/org/fossasia/openevent/app/data/db/DatabaseRepository.java
app/src/main/java/org/fossasia/openevent/app/data/db/contract/IDatabaseRepository.java
app/src/main/java/org/fossasia/openevent/app/data/models/Event.java
app/src/test/java/org/fossasia/openevent/app/model/EventRepositoryTest.java

- Filter incomplete events in detail view
- Load from network if incomplete event found
- Batch insert mode through transaction

fix: Load complete event on detail view load

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/common/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/data/EventRepository.java
app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java
app/src/main/java/org/fossasia/openevent/app/data/contract/ILoginModel.java
app/src/main/java/org/fossasia/openevent/app/data/db/DatabaseRepository.java
app/src/main/java/org/fossasia/openevent/app/data/db/contract/IDatabaseRepository.java
app/src/main/java/org/fossasia/openevent/app/data/models/User.java
app/src/main/java/org/fossasia/openevent/app/data/models/UserDetail.java
app/src/main/java/org/fossasia/openevent/app/events/EventsPresenter.java
app/src/test/java/org/fossasia/openevent/app/db/SimpleModelTest.java
app/src/test/java/org/fossasia/openevent/app/model/EventRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/model/LoginModelTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventsPresenterTest.java

Fixes #168 
- Add organizer in persistence layer
- Create tests, and fix old ones
- Change and add API in correspondence to asynchronous code
- Update dbflow to include bug fixes

feat: Add organiser to persistence layer

---

app/src/main/java/org/fossasia/openevent/app/event/EventContainerFragment.java

Retains fragment instances for same event

---

.travis.yml
app/build.gradle

Fixes #197 
- Add Google maven repo
- Remove Android Support Repository from Travis build

chore: Move to google maven repository

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/common/BaseFragment.java
app/src/main/java/org/fossasia/openevent/app/common/di/component/AppComponent.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/AndroidModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/BarcodeModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/DataModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/PresenterModule.java
app/src/main/java/org/fossasia/openevent/app/qrscan/ScanQRActivity.java

Fixes #174 
- Refactor modules
- Add barcode module
- Scan all components to look for any dependency left to be included in dagger
- Include sub-modules in modules to create structured dependency graph
- Update Google Vision API to solve a bug for projects using RxJava
- Change Leak Canary watch to appropriate lifecycle method to avoid false positives

feat: Move all object configurations to dagger modules

---

app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java
app/src/test/java/org/fossasia/openevent/app/model/LoginModelTest.java

Fixes #213 
- Clear cached token
- Add tests

fix: Clear cached token on logout

---

app/src/main/java/org/fossasia/openevent/app/data/EventRepository.java
app/src/test/java/org/fossasia/openevent/app/model/EventRepositoryTest.java

Fixes #205 
- Load the complete event with the partial event
- Add corresponding test

feat: Load complete event on login of user

---

app/src/main/java/org/fossasia/openevent/app/common/binding/BindingAdapters.java
app/src/main/java/org/fossasia/openevent/app/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/data/models/Order.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailPresenter.java
app/src/main/res/drawable/ic_octagram.xml
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java

Fixes #184 
- Add total sales visual in Event Detail
- Add the corresponding test

feat: Show total sales of Event

---

app/src/main/java/org/fossasia/openevent/app/data/EventRepository.java
app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java
app/src/main/java/org/fossasia/openevent/app/data/UtilModel.java
app/src/main/java/org/fossasia/openevent/app/data/contract/IUtilModel.java
app/src/main/java/org/fossasia/openevent/app/data/models/User.java
app/src/main/java/org/fossasia/openevent/app/login/LoginActivity.java
app/src/test/java/org/fossasia/openevent/app/model/LoginModelTest.java

Fixes #210 
- Clear database on new user login
- Invalidate token cache from appropriate locations
- Add test

fix: Clear database and token cache on different user login

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/app/data/UtilModel.java
app/src/main/java/org/fossasia/openevent/app/data/contract/IUtilModel.java
app/src/main/java/org/fossasia/openevent/app/event/EventContainerFragment.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/contract/IAttendeesView.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailActivity.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/contract/IEventDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/contract/IEventDetailView.java
app/src/main/java/org/fossasia/openevent/app/events/EventListActivity.java
app/src/main/java/org/fossasia/openevent/app/events/EventsListAdapter.java
app/src/main/java/org/fossasia/openevent/app/events/EventsPresenter.java
app/src/main/java/org/fossasia/openevent/app/events/contract/IEventsView.java
app/src/main/res/layout/activity_event_detail.xml
app/src/main/res/layout/event_list.xml
app/src/main/res/layout/fragment_attendees.xml
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventsPresenterTest.java

Fixes #211 
- Add pull to refresh in all views
- Modify tests accordingly

feat: Add swipe to refresh in all views

---

app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/contract/IAttendeesView.java
app/src/main/java/org/fossasia/openevent/app/events/EventListActivity.java
app/src/main/java/org/fossasia/openevent/app/events/EventsPresenter.java
app/src/main/java/org/fossasia/openevent/app/events/contract/IEventsView.java
app/src/main/res/layout/empty_layout.xml
app/src/main/res/layout/event_list.xml
app/src/main/res/layout/fragment_attendees.xml
app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventsPresenterTest.java

- Adds showEmptyView method in interface
- Hides empty view on page start
- Hides empty view on swipe refresh
- Modifies empty view layout
fixes #222

fix: Correct empty view display

---

README.md

- Also adds development guideline including project setup
fix #226

Updates README.md to include libraries used

---

app/src/test/java/org/fossasia/openevent/app/model/EventRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java

Fixes #232 
- Fix variable name errors
- Fix stubs

fix: Test errors and stubs

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/data/models/Attendee.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesPresenter.java
app/src/main/java/org/fossasia/openevent/app/utils/SearchUtils.java
app/src/main/res/drawable/ic_search.xml
app/src/main/res/menu/menu_attendees.xml
app/src/main/res/values/strings.xml

- Adds search view in action bar for attendees fragment
- Implements fuzzy search filtering with minimum fuzzy sort partial ratio 60%
fixes #190

feat: Implements attendees filtering 

---

app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesPresenter.java
app/src/main/java/org/fossasia/openevent/app/utils/ViewUtils.java
app/src/main/res/layout/fragment_attendees.xml
app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventsPresenterTest.java

- Hides on scroll
- Hides on empty page
fixes #238

fix: Scan QR fab visibility

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/common/binding/BindingAdapters.java
app/src/main/java/org/fossasia/openevent/app/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/TicketAnalyser.java
app/src/main/java/org/fossasia/openevent/app/event/detail/contract/IEventDetailPresenter.java
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/layout/ticket_analytics.xml
app/src/main/res/layout/ticket_analytics_item.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java

Fixes #182 
- Add circular progress ticket wise analysis
- Add ticket analyzer class

feat: Show ticket wise analysis

---

app/src/main/java/org/fossasia/openevent/app/data/models/Attendee.java
app/src/main/java/org/fossasia/openevent/app/data/models/Ticket.java
app/src/test/java/org/fossasia/openevent/app/presenter/helper/TicketAnalyserTest.java

Fixes #244 
- Add tests for TicketAnalyser
Couldn't add test for presenter as TicketAnalyser is static
Will add issue for simplification of EventDetailPresenter and add solution there

test: Add tests for TicketAnalyser

---

app/src/main/java/org/fossasia/openevent/app/events/EventListActivity.java
app/src/main/res/values/strings.xml

Fixes #253 
- Add a confirmation dialog before logout

feat: Confirm before logout

---

app/src/main/java/org/fossasia/openevent/app/data/EventRepository.java
app/src/main/java/org/fossasia/openevent/app/data/models/Attendee.java
app/src/main/java/org/fossasia/openevent/app/data/models/SocialLink.java
app/src/main/java/org/fossasia/openevent/app/data/models/Ticket.java
app/src/test/java/org/fossasia/openevent/app/model/EventRepositoryTest.java

- clears table (Attendee, Event) before saving new data on force reload
fixes #255

fix: updating local database on force reload

---

app/src/main/java/org/fossasia/openevent/app/data/models/Attendee.java
app/src/main/java/org/fossasia/openevent/app/data/models/Ticket.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/TicketAnalyser.java
app/src/main/java/org/fossasia/openevent/app/event/detail/contract/IEventDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/contract/IEventDetailView.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/helper/TicketAnalyserTest.java

Fixes #250 and #258
- Move all analysis to TicketAnalyser
- Remove unnecessary methods from contract
- Simplify presenter
- Add all tests for ticket analyser

feat: Simplify Event Dashboard

---

app/src/main/java/org/fossasia/openevent/app/event/checkin/AttendeeCheckInPresenter.java
app/src/test/java/org/fossasia/openevent/app/presenter/AttendeeCheckInPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java

Fixes #245
- Add tests for AttendeeCheckInPresenter
- Fix failing tests

test: Add tests for AttendeeCheckInPresenter

---

app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java

- saves search view as field and set listener to null in onDetach.
fixes #271

fix: attendees fragment leak

---

app/src/main/java/org/fossasia/openevent/app/event/detail/TicketAnalyser.java

Fixes #273 and #274 
- Fix blocking call on computation scheduler

fix: Remove blocking call to fix synchronization errors

---

app/src/main/java/org/fossasia/openevent/app/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/events/EventListFragment.java
app/src/main/java/org/fossasia/openevent/app/events/EventsListAdapter.java
app/src/main/java/org/fossasia/openevent/app/main/MainActivity.java
app/src/main/java/org/fossasia/openevent/app/utils/DateService.java
app/src/main/java/org/fossasia/openevent/app/utils/DateUtils.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventsPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/utils/DateUtilsTest.java

Fixes #264 
- Add DateUtils and DateService
- Add tests
- Move all date related handling in DateService and DateUtils

feat: Add DateUtils and DateService with tests

---

app/src/main/res/layout/attendee_layout.xml

Fixes #262 
- Add ticket info in attendee layout

feat: Add ticket info in attendee layout

---

app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java

Fixes #284 
- Add null check on searchView

fix: Add null check on searchView

---

app/src/main/java/org/fossasia/openevent/app/common/binding/BindingAdapters.java
app/src/main/res/drawable/ic_check.xml
app/src/main/res/drawable/ic_close.xml
app/src/main/res/layout/attendee_layout.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Fixes #263
- Add check and cross icon instead of text

feat: Check attendee check in indicator

---

app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/event/checkin/AttendeeCheckInFragment.java
app/src/main/java/org/fossasia/openevent/app/qrscan/ScanQRActivity.java
app/src/main/java/org/fossasia/openevent/app/qrscan/ScanQRPresenter.java
app/src/main/java/org/fossasia/openevent/app/qrscan/contract/IScanQRPresenter.java

- modifies qr scan presenter's behaviour on barcode detection such that data never emits detected value if dialog is shown already.
fixes #230

feat: check In dialog in QR scan activity

---

README.md
app/build.gradle
app/lombok.config
app/src/main/java/org/fossasia/openevent/app/data/models/Attendee.java
app/src/main/java/org/fossasia/openevent/app/data/models/CallForPapers.java
app/src/main/java/org/fossasia/openevent/app/data/models/Copyright.java
app/src/main/java/org/fossasia/openevent/app/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/data/models/License.java
app/src/main/java/org/fossasia/openevent/app/data/models/Login.java
app/src/main/java/org/fossasia/openevent/app/data/models/LoginResponse.java
app/src/main/java/org/fossasia/openevent/app/data/models/Order.java
app/src/main/java/org/fossasia/openevent/app/data/models/SimpleModel.java
app/src/main/java/org/fossasia/openevent/app/data/models/SocialLink.java
app/src/main/java/org/fossasia/openevent/app/data/models/Ticket.java
app/src/main/java/org/fossasia/openevent/app/data/models/User.java
app/src/main/java/org/fossasia/openevent/app/data/models/UserDetail.java
app/src/main/java/org/fossasia/openevent/app/data/models/Version.java
app/src/test/java/org/fossasia/openevent/app/presenter/AttendeePresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/helper/TicketAnalyserTest.java
scripts/delombok.sh

Fixes #288 
- Add lombok for code generation
- Remove BaseModel from super class

feat: Add lombok for data classes

---

app/src/main/java/org/fossasia/openevent/app/utils/DateUtils.java
app/src/main/res/layout/bottomsheet_attendee_check_in.xml

Fixes #289 
- Add formatted date in Attendee Check-In layout

feat: Show formatted date of purchased ticket

---

app/src/main/java/org/fossasia/openevent/app/data/repository/AttendeeRepository.java
app/src/main/java/org/fossasia/openevent/app/data/repository/EventRepository.java
app/src/test/java/org/fossasia/openevent/app/model/AttendeeRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/model/EventRepositoryTest.java

fix: clear previous data on swipe refresh

---

app/src/main/java/org/fossasia/openevent/app/event/checkin/AttendeeCheckInFragment.java

fix: added missing execute pending binding call

---

app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/utils/SearchUtils.java
app/src/test/java/org/fossasia/openevent/app/utils/SearchUtilsTest.java

Fixes #310 
- Extract common string from search loop and add tests

fix: Extract common string from loop and add search tests

---

app/src/main/java/org/fossasia/openevent/app/common/BaseActivity.java
app/src/main/java/org/fossasia/openevent/app/common/BaseFragment.java
app/src/main/java/org/fossasia/openevent/app/common/contract/presenter/IBasePresenter.java
app/src/main/java/org/fossasia/openevent/app/common/loader/PresenterLoader.java
app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/events/EventListFragment.java
app/src/main/java/org/fossasia/openevent/app/login/LoginActivity.java
app/src/main/java/org/fossasia/openevent/app/main/MainActivity.java
app/src/main/java/org/fossasia/openevent/app/qrscan/ScanQRActivity.java

feat: presenters via loaders

---

app/src/main/java/org/fossasia/openevent/app/main/MainActivity.java

- Call fragment transaction after drawer has closed
Fixes #324

fix: Remove navigation select lag

---

README.md
app/build.gradle
app/proguard-rules.pro
app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java
app/src/main/java/org/fossasia/openevent/app/common/ContextManager.java
app/src/main/java/org/fossasia/openevent/app/common/rx/Logger.java
app/src/main/java/org/fossasia/openevent/app/events/EventsPresenter.java
app/src/main/java/org/fossasia/openevent/app/main/MainPresenter.java
app/src/test/java/org/fossasia/openevent/app/presenter/EventsPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/MainPresenterTest.java
build.gradle

Fixes #302 
- Add sentry integration
- Add contextmanager to set and destroy sentry context
- Redirect error and info logs to sentry

feat: Add sentry integration

---

app/src/main/res/layout/fragment_attendees.xml
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/layout/fragment_event_list.xml

fix: swipe refresh layout is enclosed by frame layout

---

app/build.gradle
app/proguard-rules.pro
app/src/main/java/org/fossasia/openevent/app/event/detail/ChartAnalyser.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/contract/IEventDetailView.java
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/layout/ticket_analytics.xml
app/src/main/res/values/dimens.xml
app/src/test/java/org/fossasia/openevent/app/presenter/EventDetailPresenterTest.java

Fixes #261
- Add chart view for ticket analytics
- Add chart mutator for handling analytics logic

feat: Add ticket chart analytics

---

app/src/main/res/layout/bottomsheet_attendee_check_in.xml

fix: attendee click crash

---

app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/event/detail/contract/IEventDetailView.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/bottomsheet_attendee_check_in.xml
app/src/main/res/layout/empty_layout.xml
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/layout/fragment_event_list.xml
app/src/main/res/layout/login_activity.xml
app/src/main/res/layout/ticket_analytics.xml
app/src/main/res/layout/ticket_analytics_item.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Event Detail Page UI Modification

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/DataModule.java
app/src/main/java/org/fossasia/openevent/app/data/LoginModel.java
app/src/main/java/org/fossasia/openevent/app/data/SharedPreferenceModel.java
app/src/main/java/org/fossasia/openevent/app/data/UtilModel.java
app/src/main/java/org/fossasia/openevent/app/data/contract/ISharedPreferenceModel.java
app/src/main/java/org/fossasia/openevent/app/data/contract/IUtilModel.java
app/src/main/java/org/fossasia/openevent/app/login/LoginPresenter.java
app/src/main/java/org/fossasia/openevent/app/main/MainPresenter.java
app/src/test/java/org/fossasia/openevent/app/model/LoginModelTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/LoginPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/presenter/MainPresenterTest.java

To be merged after #301 
fixes #345

chore: Break UtilModel into SharedPreferenceModel

---

app/src/main/java/org/fossasia/openevent/app/common/data/models/Ticket.java
app/src/main/java/org/fossasia/openevent/app/common/utils/core/CompareUtils.java
app/src/main/java/org/fossasia/openevent/app/module/tickets/TicketsPresenter.java

fix: order the tickets on tickets page

---

app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/AttendeeCheckInPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/list/AttendeesPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/qrscan/ScanQRPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/list/EventsPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/login/LoginPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/main/MainPresenter.java

- removes attach and detach methods from presenters with the only super method.
fixes #363

chore: removes unnecessary methods from presenters

---

app/src/main/java/org/fossasia/openevent/app/common/app/di/component/AppComponent.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/ChangeListenerModule.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/PresenterModule.java
app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseBottomSheetFragment.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/Ticket.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/TicketRepository.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/contract/ITicketRepository.java
app/src/main/java/org/fossasia/openevent/app/common/utils/core/DateUtils.java
app/src/main/java/org/fossasia/openevent/app/module/main/MainActivity.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/CreateTicketFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/CreateTicketPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/TicketBinder.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/contract/ICreateTicketPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/contract/ICreateTicketView.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsAdapter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/contract/ITicketsPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/contract/ITicketsView.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/viewholder/TicketViewHolder.java
app/src/main/res/drawable/ic_add.xml
app/src/main/res/layout/ticket_create_form.xml
app/src/main/res/layout/ticket_create_layout.xml
app/src/main/res/layout/tickets_fragment.xml
app/src/main/res/values/strings.xml

Fixes #267 
- Add ticket POST methods in service and repository
- Add ticket database change listener
- Create view and presenter for creating tickets
- Add ticket binder for binding layout to ticket fields
- Add create ticket FAB in tickets page
- Fix format for ISO date in DateUtils
- Add base dialog fragment
- Add appropriate icons
- Fix event serialization by ignoring it
- Make ticket fields class type in order to ignore nulls
- Create intermediate field for observing creation

feat: Add create ticket feature

---

app/proguard-rules.pro
app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java
app/src/main/java/org/fossasia/openevent/app/common/app/ContextManager.java
app/src/main/java/org/fossasia/openevent/app/common/utils/core/CurrencyUtils.java
app/src/main/java/org/fossasia/openevent/app/module/main/MainPresenter.java

- Move sentry config in release block
- Make CurrencyUtils and ContextManager reactive
- Fix multiple loading of dashboard
- Fix proguard rules for release build
Fixes #367

feat: Enable lazy initialisation of app

---

app/src/main/java/org/fossasia/openevent/app/common/contract/Pipe.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/Ticket.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/TicketRepository.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/contract/ITicketRepository.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsAdapter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/contract/ITicketsPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/contract/ITicketsView.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/viewholder/TicketViewHolder.java
app/src/main/res/layout/ticket_layout.xml

- Remove automatic attendee download on getting tickets
- Add delete method in event service, ticket repository and presenter
- Use data binding to show intermediate state of ticket deleting
Fixes #359

feat: Add delete ticket functionality

---

app/src/main/java/org/fossasia/openevent/app/common/data/models/Ticket.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/TicketRepository.java
app/src/main/res/layout/ticket_layout.xml

fix: Rename ticket POST endpoint and ignore deleting attribute

---

app/src/main/java/org/fossasia/openevent/app/common/data/repository/TicketRepository.java

fix: Add network check for creating and deleting tickets

---

app/src/main/java/org/fossasia/openevent/app/module/ticket/create/CreateTicketFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/CreateTicketPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/TicketBinder.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/contract/ICreateTicketPresenter.java

- Make final Ticket in presenter
- Make Ticket binder set the ticket to binding
Fixes #392

feat: Persist created ticket on rotation

---

app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/AttendeeCheckInFragment.java
app/src/main/res/layout/bottomsheet_attendee_check_in.xml

- Use BaseBottomSheetFragment for base class'
- Use ItemPadding for layout style
Fixes #387

refactor: Use generic class and style for check in view

---

app/src/main/java/org/fossasia/openevent/app/common/app/ContextManager.java
app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/presenter/BasePresenter.java
app/src/main/java/org/fossasia/openevent/app/common/data/Bus.java
app/src/main/java/org/fossasia/openevent/app/module/main/MainActivity.java
app/src/main/java/org/fossasia/openevent/app/module/main/MainPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/main/contract/IMainView.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/CreateTicketPresenter.java

- Make Bus of PublishSubject type
- Set event in ContextManager
- Make BasePresenter rotation aware
- Refactor Main activity and presenter for fine grain
logic control
- Add rotation aware persistence logic in MainPresenter
Fixes #376, Fixes #375, Fixes #368

feat: Make main presenter behavior persistent

---

app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseFragment.java
app/src/main/java/org/fossasia/openevent/app/common/utils/ui/ViewUtils.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/list/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/module/auth/login/LoginFragment.java
app/src/main/java/org/fossasia/openevent/app/module/auth/signup/SignUpFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/list/EventListFragment.java
app/src/main/java/org/fossasia/openevent/app/module/main/MainActivity.java
app/src/main/java/org/fossasia/openevent/app/module/settings/SettingsFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsFragment.java

- Create general setTitle method in ViewUtils
- Remove title setter from MainActivity
- Create abstract method getTitle in BaseFragment
Fixes #390

feat: Move titles in respective fragments

---

app/src/main/AndroidManifest.xml
app/src/main/res/color/menu_text_color.xml
app/src/main/res/layout/header_layout.xml
app/src/main/res/layout/main_activity.xml
app/src/main/res/values-v23/styles.xml
app/src/main/res/values/colors.xml

- Make MainActivity translucent
- Add color list for menu
- Enable dark status bar for M+
Fixes #394

feat: Make app completely light

---

app/src/main/java/org/fossasia/openevent/app/common/app/di/component/AppComponent.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/PresenterModule.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/TicketRepository.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/contract/ITicketRepository.java
app/src/main/java/org/fossasia/openevent/app/common/utils/ui/ViewUtils.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/detail/TicketDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/detail/TicketDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/detail/contract/ITicketDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/detail/contract/ITicketDetailView.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsAdapter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/contract/ITicketsPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/contract/ITicketsView.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/viewholder/TicketViewHolder.java
app/src/main/res/layout/ticket_detail_layout.xml
app/src/main/res/layout/ticket_layout.xml

- Add Ticket Detail View and Presenter
- Add ticket list click handler
- Add getTicket method in EventService and Repository
- Add presenter and view in DI
Fixes #353

feat: Create ticket detail view

---

app/src/main/res/layout/login_fragment.xml
app/src/main/res/layout/sign_up_fragment.xml

feat: show password button on auth pages

---

app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java

Fixes #409
- Remove default pagination

fix: Remove pagination from API requests

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java
app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseActivity.java

- Make OrgApplication extend MultidexApplication
- Enable static vector resource option
Fixes #408

fix: Enable multidex and vector support pre-lollipop

---

app/build.gradle

Fixes #417 
- Add support multidex lib
- Force apply on all configurations

fix: Force support multidex on all configurations

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java
app/src/main/java/org/fossasia/openevent/app/common/utils/core/DateUtils.java
app/src/main/java/org/fossasia/openevent/app/common/utils/core/service/DateService.java
app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/analyser/ChartAnalyser.java
app/src/main/java/org/fossasia/openevent/app/module/settings/SettingsFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/CreateTicketPresenter.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/EventsPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/unit/utils/DateUtilsTest.java

Fixes #413 
- Add threetenabp
- Add rigorous tests
> Note to self. Date Handling in Java is difficult

feat: Add threetenabp and refactor DateUtils

---

app/src/main/java/org/fossasia/openevent/app/common/app/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/HostSelectionInterceptor.java
app/src/main/java/org/fossasia/openevent/app/module/auth/login/LoginFragment.java
app/src/main/java/org/fossasia/openevent/app/module/auth/login/LoginPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/auth/login/contract/ILoginPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/auth/signup/SignUpFragment.java
app/src/main/java/org/fossasia/openevent/app/module/auth/signup/SignUpPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/auth/signup/contract/ISignUpPresenter.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/LoginPresenterTest.java

- Make DI graph provide Retrofit instead of Builder
- Fix presenter base url change API
Fixes #423

fix: Make HostSelectionInterceptor Singleton

---

app/src/main/java/org/fossasia/openevent/app/common/app/binding/DateBindings.java
app/src/main/java/org/fossasia/openevent/app/common/data/db/configuration/ObservableStringTypeConverter.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/Ticket.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/dto/ObservableString.java
app/src/main/java/org/fossasia/openevent/app/common/utils/json/ObservableStringDeserializer.java
app/src/main/java/org/fossasia/openevent/app/common/utils/json/ObservableStringSerializer.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/CreateTicketPresenter.java
app/src/main/res/layout/ticket_create_form.xml
app/src/main/res/values/strings.xml

To be merged after #415 
- Add date/time pickers in layout
- Create Date bindings
- Add observable fields in ticket
- Verify dates in presenter
Fixes #419

feat: Add date time pickers in create ticket layout

---

app/src/main/java/org/fossasia/openevent/app/module/event/chart/ChartActivity.java
app/src/main/res/layout/activity_chart.xml
app/src/main/res/layout/fragment_attendees.xml
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/layout/fragment_event_list.xml
app/src/main/res/layout/login_fragment.xml
app/src/main/res/layout/progressbar_layout.xml
app/src/main/res/layout/sign_up_fragment.xml
app/src/main/res/layout/tickets_fragment.xml

- modified progress bar views in all the layouts
fixes #412

fix: disable background clicks when progress bar is shown

---

app/src/main/java/org/fossasia/openevent/app/common/app/rx/ViewTransformers.java
app/src/main/java/org/fossasia/openevent/app/common/utils/core/ErrorUtils.java
app/src/main/java/org/fossasia/openevent/app/common/utils/ui/ViewUtils.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/AttendeeCheckInFragment.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/list/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/module/auth/login/LoginFragment.java
app/src/main/java/org/fossasia/openevent/app/module/auth/signup/SignUpFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/chart/ChartActivity.java
app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/list/EventListFragment.java
app/src/main/java/org/fossasia/openevent/app/module/main/MainActivity.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/CreateTicketFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/detail/TicketDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsFragment.java

- created ErrorUtils which takes throwable and returns a good error message.
- added method in view utils to show a custom snackbar with margins
fixes #266

feat: API error handling

---

app/src/main/java/org/fossasia/openevent/app/module/attendee/list/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/list/EventListFragment.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsFragment.java

- Create recyclerview boilerplate only once
- Set all listeners on resume
- Disable backup
Fixes #439

fix: Set listeners on resume and disable backup

---

app/src/main/java/org/fossasia/openevent/app/common/data/repository/AttendeeRepository.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/AttendeeCheckInFragment.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/AttendeeCheckInPresenter.java
app/src/main/res/drawable/ic_local_sync.xml
app/src/main/res/drawable/ic_server_sync.xml
app/src/main/res/layout/attendee_layout.xml
app/src/main/res/layout/bottomsheet_attendee_check_in.xml
app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java

- Modified scheduleToggle method to update the attendee locally first before adding the job to the queue.
- Added ticks icon to the attendee layout and bottom sheet layout to show if the attendee is in sync with the server.
- Modified check in status icon in the attendee layout
- Modified attendee bottom sheet layout behavior for the above changes.
fixes #450

fix: Improve Offline Support to the Attendee Check In

---

app/src/main/res/layout/bottomsheet_attendee_check_in.xml

Fixes #457 
- Apply margin
- Remove FrameLayout

fix: Apply margin to attendee check in FAB

---

app/src/main/java/org/fossasia/openevent/app/module/attendee/list/AttendeesFragment.java
app/src/main/res/drawable/ic_filter.xml
app/src/main/res/menu/menu_attendees.xml
app/src/main/res/values/strings.xml

- Added filter by pending sync
fixing #452

feat: Enhance Attendees Page

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/common/app/binding/BindingAdapters.java
app/src/main/res/layout/main_nav_header.xml

- added bindNavHeader binding adapter method to generate a palette for the event detail palette
- modified nav header layout for the changes
fixes #455

Feat: Use Android Palette to show Event Detail Panel in Nav header

---

app/src/main/java/org/fossasia/openevent/app/common/data/AuthModel.java
app/src/main/java/org/fossasia/openevent/app/module/event/list/EventsListAdapter.java
app/src/main/res/layout/event_layout.xml

- added check icon in event layout with visibility case
- set context event to null on logout
fixes #474

feat: show selected event marked in events list

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/common/app/rx/ViewTransformers.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/contract/IAboutEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/contract/IAboutEventVew.java
app/src/main/java/org/fossasia/openevent/app/module/event/list/EventListFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/list/EventsPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/list/contract/IEventsPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/list/contract/IEventsView.java
app/src/main/java/org/fossasia/openevent/app/module/organizer/detail/OrganizerDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/module/organizer/detail/OrganizerDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/organizer/detail/contract/IOrganizerDetailPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/organizer/detail/contract/IOrganizerDetailView.java
app/src/main/res/layout/about_event_fragment.xml
app/src/main/res/layout/organizer_detail_fragment.xml
app/src/test/java/org/fossasia/openevent/app/unit/presenter/EventsPresenterTest.java

Fixes #477
- Make detail views refreshable
- Add new composite Rx Transformer
- Disable findbugs fail on error

feat: Make detail views refreshable

---

app/src/main/java/org/fossasia/openevent/app/common/app/binding/BindingAdapters.java
app/src/main/java/org/fossasia/openevent/app/common/utils/ui/ViewUtils.java
app/src/main/java/org/fossasia/openevent/app/module/auth/login/LoginFragment.java
app/src/main/java/org/fossasia/openevent/app/module/auth/signup/SignUpFragment.java
app/src/main/res/layout/auth_url_container.xml
app/src/main/res/layout/login_fragment.xml
app/src/main/res/layout/sign_up_fragment.xml

- added data variable action of type runnable to auth url container layout
- changed parameter of ViewUtils.hideKeyboard to View
- added hideKeyboard call in data binding Go
fixes #425

feat: Go Button on Alternate Base URL field

---

app/src/main/java/org/fossasia/openevent/app/common/data/models/Attendee.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/AttendeeRepository.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/AttendeeCheckInFragment.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/AttendeeCheckInPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/contract/IAttendeeCheckInView.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/list/AttendeesPresenter.java
app/src/main/res/layout/bottomsheet_attendee_check_in.xml
app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeePresenterTest.java

- Add order relation in Attendee
- Modify API requests for it
- Modify layout files
- Fix model partial update
- Remove redundant view methods and tests
Fixes #479

feat: Complete Order API support

---

app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardPresenter.java
app/src/test/java/org/fossasia/openevent/app/unit/model/EventRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/EventDashboardPresenterTest.java

To be merged after #476 
- relevant tests are added to event dashboard and list presenters
fixes #481

test: Event State Toggling

---

app/src/main/java/org/fossasia/openevent/app/module/main/MainActivity.java

- added case to check the selected menu item id with last one in loadFragment method
fixes #494

fix: Don't reload the page on selected the same menu item

---

app/src/main/java/org/fossasia/openevent/app/common/data/repository/TicketRepository.java
app/src/test/java/org/fossasia/openevent/app/robo/db/TicketTest.java
app/src/test/java/org/fossasia/openevent/app/unit/model/TicketRepositoryTest.java

test: Add TicketRepository tests

---

app/src/test/java/org/fossasia/openevent/app/unit/presenter/TicketsPresenterTest.java

- added tests for tickets presenter
fixes #506

test: TicketsPresenter

---

app/build.gradle
app/src/test/java/org/fossasia/openevent/app/unit/presenter/MainPresenterTest.java

- Mockito core is replaced to inline to allow final class mock
- tests added for MainPresenter
fixes #499

test: MainPresenter

---

app/src/test/java/org/fossasia/openevent/app/unit/model/AuthModelTest.java

- added test for clearing selected event on logout
fixes #503

test: AuthModel

---

app/src/test/java/org/fossasia/openevent/app/unit/presenter/SignUpPresenterTest.java

- added tests for signup presenter
fixes #508

test: SignUpPresenter

---

app/src/test/java/org/fossasia/openevent/app/unit/presenter/TicketCreatePresenterTest.java

test: Add ticket create presenter tests

---

app/src/main/java/org/fossasia/openevent/app/common/utils/ui/ViewUtils.java
app/src/test/java/org/fossasia/openevent/app/unit/utils/ui/ViewUtilsTest.java

Fixes #511 
- Add ViewUtils unit tests

test: ViewUtils Unit Tests

---

app/src/main/java/org/fossasia/openevent/app/common/utils/core/service/DateService.java
app/src/test/java/org/fossasia/openevent/app/unit/utils/DateServiceTest.java

Fixes #505 Fixes #306
- Add DateService tests
- Fix DateService  bugs

test: Add DateService tests and fix bugs

---

app/src/main/java/org/fossasia/openevent/app/common/data/db/configuration/OrgaDatabase.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/Attendee.java

Fixes #523 
- Bump DB version
- Add missing attributes to Attendee

feat: Add missing attendee attributes

---

app/src/main/res/drawable/ic_account_circle.xml

fix: Replace distorted account circle

---

app/src/main/java/org/fossasia/openevent/app/common/data/db/configuration/OrgaDatabase.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/Attendee.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/AttendeeRepository.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/AttendeeCheckInPresenter.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/AttendeeCheckInPresenterTest.java

Fixes #528
- Add migration 8 - for Attendee attribute
- Refactor model changes from repository to presenter
- Add check in time before each toggle request

fix: Add attendee checkin-times

---

app/build.gradle

Fixes #534 
- Resolve ambiguous dependency of OkHttp

fix: Resolve okhttp conflict

---

.gitignore

Fixes #532 
- Add app/*apk to gitignore

chore: Ignore apk files

---

app/src/main/java/org/fossasia/openevent/app/module/auth/login/LoginFragment.java

* fix: keyboard should be closed and then Snackbar should be visible to the user.

Fixes #538 : Keyboard Closing in LoginFragment Updated

---

scripts/update-apk.sh

Fixes #536 
- Modify update-apk.sh to accomodate DEPLOY_BRANCH and PUBLISH_BRANCH

chore: Generate apps from development branch

---

README.md

chore: Change build badge status to development branch

---

app/build.gradle

chore: v4 update

---

.travis.yml
app/build.gradle
app/config/pmd.xml
app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java
app/src/main/java/org/fossasia/openevent/app/common/app/binding/ImageBindings.java
app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseBottomSheetFragment.java
app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseFragment.java
app/src/main/java/org/fossasia/openevent/app/common/data/db/DatabaseRepository.java
app/src/main/java/org/fossasia/openevent/app/common/data/db/QueryHelper.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/delegates/AttendeeDelegate.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/TicketRepository.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/contract/ITicketRepository.java
app/src/main/java/org/fossasia/openevent/app/common/utils/ui/PaletteHolder.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/AttendeeCheckInFragment.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/job/AttendeeCheckInJob.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/list/AttendeesFragment.java
app/src/main/java/org/fossasia/openevent/app/module/attendee/list/StickyHeaderAdapter.java
app/src/main/res/layout/fragment_event_details.xml
app/src/test/java/org/fossasia/openevent/app/robo/db/BaseTest.java
app/src/test/java/org/fossasia/openevent/app/robo/db/DatabaseChangeListenerTest.java
app/src/test/java/org/fossasia/openevent/app/robo/db/DatabaseRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/robo/db/TicketTest.java
app/src/test/java/org/fossasia/openevent/app/robo/ui/ActivityInstanceTest.java
app/src/test/java/org/fossasia/openevent/app/robo/ui/BaseParameterTest.java
app/src/test/java/org/fossasia/openevent/app/robo/ui/FragmentInstanceTest.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/TicketsPresenterTest.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

chore: Update libs, SDK and gradle

---

README.md

chore: Update codacy badge

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardFragment.java
app/src/main/res/layout/fragment_event_details.xml

Fixes #357 
Changes: Refactored the layout to use Constraint Layout in EventDetail Fragment.
Screenshot: Nothing has changed in terms of outlook.
Sorry about the previous PR.

fix: Using constraint layout for the EventDetail Fragment

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

Fixes #560 
Changes: Added issues and PR templates
Screenshot: NA

Added issues and PR templates

---

app/src/main/java/org/fossasia/openevent/app/common/app/di/component/AppComponent.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/PresenterModule.java
app/src/main/java/org/fossasia/openevent/app/common/data/AuthModel.java
app/src/main/java/org/fossasia/openevent/app/common/data/contract/IAuthModel.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/SubmitToken.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/SubmitTokenResponse.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/module/auth/forgot/password/token/request/ForgotPasswordFragment.java
app/src/main/java/org/fossasia/openevent/app/module/auth/forgot/password/token/request/ForgotPasswordPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/auth/forgot/password/token/request/contract/IForgotPasswordPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/auth/forgot/password/token/request/contract/IForgotPasswordView.java
app/src/main/java/org/fossasia/openevent/app/module/auth/forgot/password/token/submit/ResetPasswordByTokenFragment.java
app/src/main/java/org/fossasia/openevent/app/module/auth/forgot/password/token/submit/ResetPasswordByTokenPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/auth/forgot/password/token/submit/contract/IResetPasswordByTokenPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/auth/forgot/password/token/submit/contract/IResetPasswordByTokenView.java
app/src/main/res/layout/forgot_password_fragment.xml
app/src/main/res/layout/reset_password_by_token_fragment.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/robo/ui/FragmentInstanceTest.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/ForgotPasswordPresenterTest.java

fixes #578
parent #548
Changes: User enters the token  he received via email along ith new password to change his account's password in case he forgots it.

feature: Enter recovery token to request new password

---

app/src/test/java/org/fossasia/openevent/app/unit/presenter/ResetPasswordByTokenPresenterTest.java

Fixes #584 
Changes: Added JunitTests for ResetPasswordByTokenPresenter.

test: Unit Tests for ResetPasswordByTokenPresenter

---

app/src/main/java/org/fossasia/openevent/app/common/app/di/component/AppComponent.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/PresenterModule.java
app/src/main/java/org/fossasia/openevent/app/common/data/AuthModel.java
app/src/main/java/org/fossasia/openevent/app/common/data/contract/IAuthModel.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/ChangePassword.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/ChangePasswordResponse.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/utils/core/ErrorUtils.java
app/src/main/java/org/fossasia/openevent/app/module/organizer/detail/OrganizerDetailActivity.java
app/src/main/java/org/fossasia/openevent/app/module/organizer/detail/OrganizerDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/module/organizer/password/ChangePasswordFragment.java
app/src/main/java/org/fossasia/openevent/app/module/organizer/password/ChangePasswordPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/organizer/password/contract/IChangePasswordPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/organizer/password/contract/IChangePasswordView.java
app/src/main/res/drawable/ic_password.xml
app/src/main/res/layout/change_password_fragment.xml
app/src/main/res/layout/organizer_detail_activity.xml
app/src/main/res/layout/organizer_detail_fragment.xml
app/src/main/res/menu/menu_organizer.xml
app/src/main/res/values/strings.xml

Fixes #581 
Changes: Now a user after logging in the application can change his password whenever required.

feat: Change password feature for logged In user

---

app/src/test/java/org/fossasia/openevent/app/unit/presenter/ChangePasswordPresenterTest.java

test: JUnit tests for ChangePasswordPresenter

---

.circleci/config.yml

Fixes #597 
Changes: 
- Add circle CI configuration for project

chore: Add circle CI config

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/app/common/app/di/component/AppComponent.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/PresenterModule.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/EventRepository.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/Repository.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/contract/IEventRepository.java
app/src/main/java/org/fossasia/openevent/app/common/utils/core/service/DateService.java
app/src/main/java/org/fossasia/openevent/app/module/event/create/CreateEventActivity.java
app/src/main/java/org/fossasia/openevent/app/module/event/create/CreateEventFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/create/CreateEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/create/contract/ICreateEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/create/contract/ICreateEventView.java
app/src/main/java/org/fossasia/openevent/app/module/event/list/EventListFragment.java
app/src/main/res/layout/create_event_activity.xml
app/src/main/res/layout/event_create_form.xml
app/src/main/res/layout/event_create_layout.xml
app/src/main/res/layout/event_layout.xml
app/src/main/res/layout/fragment_event_list.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/robo/db/TicketTest.java
app/src/test/java/org/fossasia/openevent/app/unit/model/EventRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/EventDashboardPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/EventsPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/unit/presenter/MainPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/unit/utils/DateServiceTest.java

Fixes #518 
Changes: User can now create Event in the app with mandatory fields.

feat: Added option to Create Event

---

app/src/main/java/org/fossasia/openevent/app/common/utils/ui/PaletteHolder.java

fix: Resolved Findbugs violations

---

app/src/test/java/org/fossasia/openevent/app/robo/ui/ActivityInstanceTest.java

fix: ActivityInstanceTest on CreateEventActivity

---

app/src/test/java/org/fossasia/openevent/app/unit/model/EventRepositoryTest.java

test: Create Event test in EventRepository

---

app/src/main/java/org/fossasia/openevent/app/common/utils/core/CurrencyUtils.java
app/src/main/java/org/fossasia/openevent/app/module/main/MainPresenter.java

Fixes #601 
Changes: App logs error on null payment currency code
Screenshots for the change:  Not applicable

fix: Crash on null Currency Code

---

app/src/main/java/org/fossasia/openevent/app/common/app/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/common/data/models/EventStatistics.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/EventRepository.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/contract/IEventRepository.java
app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/contract/IEventDashboardView.java
app/src/main/res/layout/event_statistics.xml
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/unit/presenter/EventDashboardPresenterTest.java

Fixes #633 
Changes: User can view or hide Event Statistics in app's Dashboard.

feat: View Event Statistics in Dashboard

---

app/src/main/java/org/fossasia/openevent/app/common/app/binding/DateBindings.java
app/src/main/java/org/fossasia/openevent/app/module/event/create/CreateEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/ticket/create/CreateTicketPresenter.java

Fixes #638 
Changes: app does not crash while creating new ticket or event
Screenshots for the change(UPDATED):

fix: app does not crash while creating new ticket or event

---

app/src/main/res/drawable/ic_bank.xml
app/src/main/res/drawable/ic_cheque.xml
app/src/main/res/drawable/ic_payment.xml
app/src/main/res/layout/about_event_detail.xml

Fixes #617 
Changes: Added all the options related to an event in about fragment.

feat: Show All Details of Event in About Section

---

app/build.gradle

Fixes #670 
Changes: Updated build.gradle 
Screenshots for the change:  Not applicable

chore: Update libs version

---

app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/AttendeeCheckInFragment.java
app/src/main/res/drawable/ic_home.xml
app/src/main/res/layout/bottomsheet_attendee_check_in.xml
app/src/main/res/values/strings.xml

Fixes #665 
Changes: Show Attendee Details

fix: Show Attendee Details

---

app/src/main/java/org/fossasia/openevent/app/common/data/network/HostSelectionInterceptor.java

Fixes #675
Changes: 
- Parse port from URL input and set it in the interceptot

fix: Parse port from the URL input

---

app/src/main/res/layout/about_event_detail.xml
app/src/main/res/layout/bottomsheet_attendee_check_in.xml
app/src/main/res/layout/organizer_detail_layout.xml

Fixed showing unknown info from UI #628 #651
Changes: 
fixed the issue in 3 views,
1. organizer_detail_layout.xml which shows organizer details
2. about_event_details.xml which shows event details
3. bottomsheet_attendee_check_in.xml which popup from bottom when an attendee is selected
Here is a screenshot before the fix
Here are the screenshots after fix

Fixed showing unknown info from UI issue #628

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/common/Constants.java

Fixes #680 
Changes
changed the base URL to  https://open-event-api-dev.herokuapp.com

Fixes #680 changed the base URL

---

app/src/main/res/layout/ticket_detail_layout.xml

Fixes #695 
Changes: Safe Unboxing added to prevent Null Pointer Exception
Screenshots for the change:  Not applicable

fix: Data Binding NPE warning

---

app/src/main/java/org/fossasia/openevent/app/common/utils/core/CurrencyUtils.java

Fixes #698 
Changes: Added few important currencies at the top and sorted rest alphabetically in currency list.

feat:  Sort Currency list on priority basis (#698)

---

app/build.gradle
app/config.gradle

Fix #659: Add Config.gradle file for package version

---

app/src/main/java/org/fossasia/openevent/app/common/utils/core/CurrencyUtils.java

Fixes #718 
Changes: There were several instances of same currencies which have been removed now.

bug: Remove multiple instances of currencies from currency list (#718)

---

app/src/test/java/org/fossasia/openevent/app/unit/presenter/TicketCreatePresenterTest.java

Fixes #713 
Changes: Included tests for progress bar.
Screenshots for the change:  NA

test: Update tests for CreateTicketPresenter

---

app/src/main/java/org/fossasia/openevent/app/common/app/di/component/AppComponent.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/DataModule.java
app/src/main/java/org/fossasia/openevent/app/common/app/di/module/PresenterModule.java
app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/FaqRepository.java
app/src/main/java/org/fossasia/openevent/app/common/data/repository/contract/IFaqRepository.java
app/src/main/java/org/fossasia/openevent/app/module/faq/create/CreateFaqFragment.java
app/src/main/java/org/fossasia/openevent/app/module/faq/create/CreateFaqPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/faq/create/contract/ICreateFaqPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/faq/create/contract/ICreateFaqView.java
app/src/main/java/org/fossasia/openevent/app/module/faq/list/FaqListFragment.java
app/src/main/java/org/fossasia/openevent/app/module/faq/list/FaqListPresenter.java
app/src/main/res/layout/faq_create_form.xml
app/src/main/res/layout/faq_create_layout.xml
app/src/main/res/layout/faqs_fragment.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/unit/presenter/FaqListPresenterTest.java

Fixes #677
Changes: 
1. Added option to create FAQ.
2. Refractored the name of FAQRepository to FaqRepository to maintain uniformity throughout the codebase.

feat: Added feature to Create FAQ

---

app/src/main/res/layout/copyright_create_form.xml

Fixes #752
Changes: change the image drawable to url image

bug: Add link drawable instead of email drawable

---

app/src/test/java/org/fossasia/openevent/app/unit/presenter/CreateFaqPresenterTest.java

Fixes #725 
Changes: Created Unit tests for CreateFaqPresenter.

test: Unit tests for CreateFaqPresenter

---

app/src/test/java/org/fossasia/openevent/app/unit/presenter/TicketDetailPresenterTest.java

Fixes #741 
Changes: Created Unit tests for TicketDetailPresenter.

test: Unit Tests for TicketDetailPresenter

---

app/src/test/java/org/fossasia/openevent/app/unit/presenter/AboutEventPresenterTest.java

Fixes #739 
Changes: Add Unit tests for AboutEventPresenter

test: Unit Tests for AboutEventPresenter

---

app/src/test/java/org/fossasia/openevent/app/unit/utils/ValidateUtilsTest.java

Fixes #743 
Changes: Created Unit test for ValidateUtils.

test: Unit Tests for ValidateUtils

---

app/src/main/res/layout/ticket_detail_layout.xml

Fixed ticket details bug

---

app/src/main/res/layout/login_fragment.xml
app/src/main/res/values/strings.xml

Fixes #749 
Changes: Added a textview welcoming organizer and making landing page looks like it is an app for the organiser.
Updated:

Login UI Improved : Textview Added

---

app/src/main/java/org/fossasia/openevent/app/module/auth/signup/SignUpFragment.java
app/src/main/java/org/fossasia/openevent/app/module/auth/signup/SignUpPresenter.java
app/src/main/java/org/fossasia/openevent/app/module/auth/signup/contract/ISignUpPresenter.java
app/src/main/res/layout/sign_up_fragment.xml
app/src/main/res/values/strings.xml

Fixes #797 
A confirm password edittext was added to Sign Up section and the functionality was implemented.

feat:Added a confirm password to sign up

---

app/src/test/java/org/fossasia/openevent/app/robo/ui/ActivityInstanceTest.java
app/src/test/java/org/fossasia/openevent/app/robo/ui/FragmentInstanceTest.java

Fixes #686 
Changes: The Activity and Fragment instantiation tests were removed.

chore: Removed Activity and Fragment instantiation tests

---

.travis.yml
app/build.gradle
app/config.gradle

Fixes #673
Changes: 
- Update build tools version to 27.03
- Update support lib version, lombok, JSON, etc

chore: Update dependencies

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventActivity.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/contract/IAboutEventVew.java
app/src/main/java/org/fossasia/openevent/app/module/main/MainActivity.java
app/src/main/res/layout/about_event_activity.xml
app/src/main/res/menu/activity_main_drawer.xml
app/src/test/java/org/fossasia/openevent/app/robo/ui/ActivityInstanceTest.java

Reverts fossasia/open-event-orga-app#770
Several bugs related to UI render app unusable

Revert "About#751"

---

app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseActivity.java
app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseBottomSheetFragment.java
app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseFragment.java

fix: Detach presenters onStop

---

app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventFragment.java
app/src/main/java/org/fossasia/openevent/app/module/event/about/ToolbarColorChanger.java

Fixes #841 
Add isolate ToolbarColorChanger which observes collapsing toolbar changes and provides color information based on that

fix: Set color of overflow dynamically

---

app/src/main/java/org/fossasia/openevent/app/core/faq/list/viewholder/FaqViewHolder.java
app/src/main/res/drawable/ic_arrow_drop_down.xml
app/src/main/res/drawable/ic_arrow_up.xml
app/src/main/res/layout/faq_layout.xml

feat:Improved UX of faq

---

scripts/update-apk.sh

Fixes #855 
- Recursively copy apks from subfolders
- Add output JSONs to folder

fix: APK upload on build

---

app/src/main/java/org/fossasia/openevent/app/data/db/configuration/OrgaDatabase.java

chore: Migrate Database to Version 9

---

app/src/test/java/org/fossasia/openevent/app/unit/presenter/TicketDetailPresenterTest.java

Fixes #858
Done the required changes!

fix: Changed the package name in TicketDetailPresenterFragment

---

app/src/main/java/org/fossasia/openevent/app/common/di/component/AppComponent.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/EventsListAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/ticket/create/CreateTicketPresenter.java
app/src/main/java/org/fossasia/openevent/app/data/models/Event.java
app/src/main/java/org/fossasia/openevent/app/data/models/delegates/EventDelegate.java
app/src/main/java/org/fossasia/openevent/app/data/models/delegates/IEventDelegate.java
app/src/main/java/org/fossasia/openevent/app/data/repository/AttendeeRepository.java
app/src/main/java/org/fossasia/openevent/app/data/repository/EventRepository.java
app/src/main/java/org/fossasia/openevent/app/data/repository/FaqRepository.java
app/src/main/java/org/fossasia/openevent/app/data/repository/IEventRepository.java
app/src/main/java/org/fossasia/openevent/app/data/repository/Repository.java
app/src/main/java/org/fossasia/openevent/app/data/repository/TicketRepository.java
app/src/main/res/layout/event_create_form.xml
app/src/main/res/layout/event_layout.xml
app/src/main/res/layout/time_picker.xml
app/src/test/java/org/fossasia/openevent/app/robo/db/TicketTest.java
app/src/test/java/org/fossasia/openevent/app/unit/model/AttendeeRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/unit/model/EventRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/unit/model/FaqRepositoryTest.java
app/src/test/java/org/fossasia/openevent/app/unit/model/TicketRepositoryTest.java

Fixes #837
Changes: 
- Remove null fields from being serialized
- Remove redundant fields from event model
- Add syncSave method in repository to save items without deleting all of them
- Use equals to match selected event ID
- Ignore case while matching event state
- Fix UI for date/time picker
- Fix date logic in create ticket presenter

Bulk Fixes

---

app/src/main/java/org/fossasia/openevent/app/core/main/DrawerNavigator.java
app/src/main/java/org/fossasia/openevent/app/core/main/FragmentNavigator.java
app/src/main/java/org/fossasia/openevent/app/core/main/MainActivity.java
app/src/test/java/org/fossasia/openevent/app/core/main/DrawerNavigatorTest.java
app/src/test/java/org/fossasia/openevent/app/core/main/FragmentNavigatorTest.java

Fixes #868 
- Move navigation logic to separate components

refactor: Decompose MainActivity into Navigators

---

app/jacoco.gradle
app/lombok.config
app/src/main/java/org/fossasia/openevent/app/core/event/dashboard/EventDashboardFragment.java
app/src/main/java/org/fossasia/openevent/app/core/main/FragmentNavigator.java
app/src/main/java/org/fossasia/openevent/app/data/db/configuration/OrgaDatabase.java
app/src/main/java/org/fossasia/openevent/app/data/ticket/Ticket.java
app/src/main/res/layout/feedbacklist_layout.xml
app/src/main/res/layout/fragment_event_details.xml

- Set correct Database Version
- Remove redundant classes from Jacoco Reporting
- Fix DataBinding warnings for safeUnboxing
- Fix PMD Warnings
Fixes #879

fix: Maintain Jacoco Report and Warnings

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/ApiModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/ChangeListenerModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/RepoModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/android/MainFragmentBuildersModule.java
app/src/main/java/org/fossasia/openevent/app/core/faq/list/FaqListAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/main/FragmentNavigator.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksFragment.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksView.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/viewholder/TracksViewHolder.java
app/src/main/java/org/fossasia/openevent/app/data/db/configuration/OrgaDatabase.java
app/src/main/java/org/fossasia/openevent/app/data/tracks/Track.java
app/src/main/java/org/fossasia/openevent/app/data/tracks/TrackApi.java
app/src/main/java/org/fossasia/openevent/app/data/tracks/TrackRepository.java
app/src/main/java/org/fossasia/openevent/app/data/tracks/TrackRepositoryImpl.java
app/src/main/res/drawable/ic_event_note.xml
app/src/main/res/layout/track_item.xml
app/src/main/res/layout/tracks_fragment.xml
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/values/strings.xml

Fixes #872 
Changes: Implmented Tracks module
Fetched Tracks for an Event
Saved it in the database for offline use
Show it in a RecyclerView

feat: Show Tracks under an Event

---

app/src/test/java/org/fossasia/openevent/app/core/presenter/CreateTracksPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/core/presenter/TracksPresenterTest.java

Fixes #909 
Changes: The tests for CreateTracks and TrackPresenter were created.

chore:Created tests for tracks

---

app/src/main/java/org/fossasia/openevent/app/core/faq/list/FaqListFragment.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksFragment.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksView.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/viewholder/TracksViewHolder.java
app/src/main/java/org/fossasia/openevent/app/data/tracks/TrackApi.java
app/src/main/java/org/fossasia/openevent/app/data/tracks/TrackRepository.java
app/src/main/java/org/fossasia/openevent/app/data/tracks/TrackRepositoryImpl.java
app/src/main/res/layout/track_item.xml
app/src/main/res/values/strings.xml

Fixes #911 
Changes: Add a delete icon
Delete the Track on the Server and the local database

feat: Allow deleting Tracks

---

app/src/main/res/layout/ticket_create_form.xml

Fixes #801 
Changes: A 'Use Picker' checkbox is added to CreateTicketFragment, similar to that in CreateEventFragment.

feat: Add 'Use Picker' checkbox in Create Ticket fragment.. #801

---

app/src/main/java/org/fossasia/openevent/app/core/sponsor/create/CreateSponsorFragment.java
app/src/main/res/layout/sponsor_create_form.xml

bug:Added validation to edit text fields

---

app/src/main/java/org/fossasia/openevent/app/core/session/create/CreateSessionFragment.java
app/src/main/java/org/fossasia/openevent/app/core/session/create/CreateSessionPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/session/create/CreateSessionView.java
app/src/test/java/org/fossasia/openevent/app/core/presenter/CreateSessionPresenterTest.java
gradle.properties

Fixes #956 
Changes:
1. Runtime validation for fields like slides-url, audio-url, signup-url, video-url.
2. Check for end date to be after start date.
3. Added corresponding unit tests.

feat: Validation in Session Creation 

---

README.md

Fixes #969 
Changes: Added test account that can be used for testing and development purposes.

Added Test Developer Account

---

app/src/test/java/org/fossasia/openevent/app/core/presenter/SpeakersPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/data/repository/SpeakerRepositoryTest.java

Fixes #981 
Changes: Added unit tests for SpeakersPresenter and SpeakersRepository
Screenshots for the change: N/A

chore: Add tests for SpeakersPresenter and SpeakersRepository

---

build.gradle

Fixes #1003 
Changes: Downgraded the Android Plugin version for Gradle to 3.1.1.
Screenshots for the change: N/A.

fix: Build failure

---

app/src/main/java/org/fossasia/openevent/app/utils/DateUtils.java
app/src/main/res/layout/event_layout.xml
app/src/main/res/values/dimens.xml

Fixes #994 
Changes: Adds date - format same as eventbrite - to event list items

feat: Add date to event list item

---

app/src/main/java/org/fossasia/openevent/app/core/event/list/EventListFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/EventsListAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/EventsPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/event/list/EventsView.java
app/src/main/java/org/fossasia/openevent/app/data/event/EventDelegateImpl.java
app/src/main/res/drawable/bottom_nav_selector.xml
app/src/main/res/layout/fragment_event_list.xml
app/src/main/res/menu/event_list_bottom.xml
app/src/main/res/values/strings.xml

Fixes #972
Changes: Adds BottomNavigationView in Events List
Gif for the change:

Add BottomNavigationView in Events list

---

versions.gradle

Fixes #1022
Changes: Upgraded Work Manager version to 1.0.0-alpha02

chore: Upgrade Work Manager version

---

app/src/main/res/layout/attendee_layout.xml
app/src/main/res/layout/bottomsheet_attendee_check_in.xml

Fixes #1014  
Changes: Make attendee detail layout similar to that of attendee's detail layout
Screenshot:

chore: Redraw attendee detail layout

---

app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/event/create/CreateEventFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/create/CreateEventPresenter.java
app/src/main/java/org/fossasia/openevent/app/utils/Utils.java

feat: Added sharing functionality to Update Event

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/ViewModelModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/android/MainFragmentBuildersModule.java
app/src/main/java/org/fossasia/openevent/app/core/main/FragmentNavigator.java
app/src/main/java/org/fossasia/openevent/app/core/share/ShareEventFragment.java
app/src/main/java/org/fossasia/openevent/app/core/share/ShareEventView.java
app/src/main/java/org/fossasia/openevent/app/core/share/ShareEventViewModel.java
app/src/main/res/drawable/ic_more.xml
app/src/main/res/layout/share_event_layout.xml
app/src/main/res/menu/activity_main_drawer.xml

Fixes #997
Changes: 
1. User can share event details via email.
2. User can share event details via other apps too.
3. User can copy event url to clipboard.
4. Using ViewModel based implementation.
Orga App
EventBrite app
https://user-images.githubusercontent.com/23634977/40683462-5076077e-63ac-11e8-90af-1a2c1b625c96.png

feat: Fragment for Sharing Event and Copy URL

---

app/src/main/java/org/fossasia/openevent/app/core/faq/list/FaqListAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/faq/list/FaqListFragment.java
app/src/main/java/org/fossasia/openevent/app/core/faq/list/FaqListPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/faq/list/FaqListView.java
app/src/main/java/org/fossasia/openevent/app/core/faq/list/viewholder/FaqViewHolder.java
app/src/main/res/menu/menu_faqs.xml
app/src/main/res/values/styles.xml
app/src/test/java/org/fossasia/openevent/app/core/presenter/FaqListPresenterTest.java

Fixes #921 
Changes:
- The code for creating the delete option on the toolbar has been removed because, the ActionMode  handles it.
- In the ActionMode, the color of the status bar gets changed to black and hence it needs to be changed to color_top_surface, this is handled in the onCreateActionsMode( ).[[link](https://stackoverflow.com/questions/29618470/change-status-bar-color-when-entering-contextual-action-mode)]

feat:Added functionality to delete multiple faq

---

app/src/main/java/org/fossasia/openevent/app/core/session/list/SessionsFragment.java
app/src/main/java/org/fossasia/openevent/app/core/session/list/SessionsPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/session/list/SessionsView.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsFragment.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsView.java
app/src/test/java/org/fossasia/openevent/app/core/presenter/SessionsPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsPresenterTest.java

Fixes #1042
Changes: Using Contextual Action Bar Mode as a selection toolbar for edit and delete functionalities in -
1. SessionsFragment
2. SponsorsFragment.

feat: Contextual Action Bar as Selection Toolbar

---

app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksFragment.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksView.java

Fixes #1062 
Changes: 
Contextual action bar has been added to the tracks fragment.

feat: Add contextual action bar in tracks

---

.github/PULL_REQUEST_TEMPLATE
.github/PULL_REQUEST_TEMPLATE.md

Fixes #1091 
Changes: Adds a checklist to the pull request template and changes file type to markdown

chore: Add checklist to pull request template and change it to markdown

---

app/src/main/java/org/fossasia/openevent/app/core/session/create/CreateSessionFragment.java
app/src/main/java/org/fossasia/openevent/app/core/session/create/CreateSessionPresenter.java
app/src/main/res/layout/session_create_form.xml
app/src/main/res/values/strings.xml

Fixes #1085 
Checklist:
Changes:
- The user can now enter only numbers in the **Level** edit text.
- Added a spinner for selecting state of the session.

feat: Add spinner for session state

---

app/src/main/res/layout/about_event_detail.xml

Fixes #1103 
Checklist:
Changes: [Add here what changes were made in this issue and if possible provide links.]
Use `emptyToNull` to hide info when the field is empty or null

fix: Hide unknown info in about event details

---

app/src/main/java/org/fossasia/openevent/app/data/attendee/Attendee.java
app/src/main/java/org/fossasia/openevent/app/data/speaker/Speaker.java
app/src/main/res/layout/session_layout.xml

Fixes #1105  
Checklist:
Changes:
The number of warnings were reduced to 1. The warning which still persists is related to the dbflow library.
Screenshots:

fix: Reduce the build warnings

---

app/src/main/res/layout/login_fragment.xml
app/src/main/res/values/strings.xml

Fixes: #1102 
Checklist:
Changes
With reference to the changes that were discussed in the meeting the following things have been changed.
1) The login button width was made match parent
2) The welcome message was changed.
3) The forgot password text was changed.

feat:Enhance Login Screen

---

app/src/main/java/org/fossasia/openevent/app/core/sponsor/update/UpdateSponsorFragment.java

Fixes #1086 
Checklist:
Changes: URL in UpdateSponsorFragment are validated against regex as user types in.

feat: Validate URL in UpdateSponsorsFragment

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/ViewModelModule.java
app/src/main/java/org/fossasia/openevent/app/core/main/MainActivity.java
app/src/main/java/org/fossasia/openevent/app/core/main/MainPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/main/OrganizerViewModel.java
app/src/test/java/org/fossasia/openevent/app/core/main/OrganizerViewModelTest.java
app/src/test/java/org/fossasia/openevent/app/core/presenter/MainPresenterTest.java

Fixes #1114 
Checklist:
Changes: First step in refactoring Main Presenter to MVVM and separate modules. 
Added OrganizerViewModel.
Added unit tests for the view model

feat: Add OrganizerViewModel extracting related code out from Main Presenter

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/ViewModelModule.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/android/MainFragmentBuildersModule.java
app/src/main/java/org/fossasia/openevent/app/core/orders/detail/OrderDetailFragment.java
app/src/main/java/org/fossasia/openevent/app/core/orders/detail/OrderDetailView.java
app/src/main/java/org/fossasia/openevent/app/core/orders/detail/OrderDetailViewModel.java
app/src/main/java/org/fossasia/openevent/app/core/orders/list/OrdersAdapter.java
app/src/main/java/org/fossasia/openevent/app/core/orders/list/OrdersFragment.java
app/src/main/java/org/fossasia/openevent/app/core/orders/list/OrdersView.java
app/src/main/java/org/fossasia/openevent/app/core/orders/list/viewholder/OrderViewHolder.java
app/src/main/java/org/fossasia/openevent/app/data/order/Order.java
app/src/main/java/org/fossasia/openevent/app/data/order/OrderApi.java
app/src/main/java/org/fossasia/openevent/app/data/order/OrderRepository.java
app/src/main/java/org/fossasia/openevent/app/data/order/OrderRepositoryImpl.java
app/src/main/res/layout/order_detail_fragment.xml
app/src/main/res/values/strings.xml

Fixes #1101 
Checklist:
Changes: 
1. Resolved minor bugs in Order List Layout.
2. Showing Details of Orders in OrderDetailFragment.

feat: Show Order Details

---

app/src/main/java/org/fossasia/openevent/app/core/settings/EventSettingsFragment.java
app/src/main/java/org/fossasia/openevent/app/core/settings/ScanSettings.java
app/src/main/java/org/fossasia/openevent/app/core/settings/SettingsFragment.java
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/event_preferences.xml
app/src/main/res/xml/scan_settings.xml

Fixes #1089 
Checklist:
Changes: Adds Scan Settings (Check In | Check Out | Validate) in Event Settings

feat: Add Scan Settings to Event Settings

---

app/src/main/java/org/fossasia/openevent/app/core/main/DrawerNavigator.java
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/values/strings.xml

Fixes #1108 
Checklist:
Changes: A Google form was created its shareable link was added in the Intent.

feat: Add suggestions in navigation drawer

---

app/src/main/java/org/fossasia/openevent/app/core/event/create/CreateEventFragment.java
app/src/main/java/org/fossasia/openevent/app/core/faq/create/CreateFaqFragment.java
app/src/main/java/org/fossasia/openevent/app/core/faq/list/FaqListFragment.java
app/src/main/java/org/fossasia/openevent/app/core/session/create/CreateSessionFragment.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/create/CreateSponsorFragment.java
app/src/main/java/org/fossasia/openevent/app/core/sponsor/list/SponsorsFragment.java
app/src/main/java/org/fossasia/openevent/app/core/ticket/create/CreateTicketFragment.java
app/src/main/java/org/fossasia/openevent/app/core/ticket/list/TicketsFragment.java
app/src/main/java/org/fossasia/openevent/app/core/track/create/CreateTrackFragment.java
app/src/main/java/org/fossasia/openevent/app/core/track/list/TracksFragment.java
app/src/main/res/layout/event_create_form.xml
app/src/main/res/layout/event_create_layout.xml
app/src/main/res/layout/faq_create_form.xml
app/src/main/res/layout/faq_create_layout.xml
app/src/main/res/layout/session_create_form.xml
app/src/main/res/layout/session_create_layout.xml
app/src/main/res/layout/sponsor_create_form.xml
app/src/main/res/layout/sponsor_create_layout.xml
app/src/main/res/layout/ticket_create_form.xml
app/src/main/res/layout/ticket_create_layout.xml
app/src/main/res/layout/track_create_form.xml
app/src/main/res/layout/track_create_layout.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Fixes #1087 
Checklist:
Changes: 
1. Removed BaseBottomSheetFragment and used BaseFragment instead.
2. Removed `initialized` variable in list layouts to avoid situation of no adapter not getting attached on back pressed from create fragment layout.
CreateEventFragment
CreateSessionFragment
CreateTrackFragment
CreateSponsorFragment
CreateTicketFragment
CreateFaqFragment

fix: Improved UI of Creation and Updation

---

app/src/main/res/layout/update_organizer_form.xml

Fixes #1107 
Checklist:
Changes: 
1. Adds drawable fields to social media links
2. Adds hints to First name and Last name

fix: Update Organizers Details form

---

app/src/main/java/org/fossasia/openevent/app/core/auth/reset/ResetPasswordFragment.java
app/src/main/java/org/fossasia/openevent/app/core/auth/reset/ResetPasswordViewModel.java
app/src/test/java/org/fossasia/openevent/app/core/auth/reset/ResetPasswordViewModelTest.java

Fixes #1137 
Checklist:
Changes: Adds test

test: add test for ResetPasswordViewModel

---

app/src/test/java/org/fossasia/openevent/app/core/speaker/details/SpeakerDetailsViewModelTest.java

Fixes #1043 
Checklist:
Changes: Implemented tests for SpeakerDetailsViewModel

chore:Add speakerdetailsviewmodel test

---

app/src/test/java/org/fossasia/openevent/app/data/repository/SpeakerRepositoryTest.java

Fixes #1043 
Checklist:
Changes:
Speaker repository tests were updated.

chore:Update speaker repository tests

---

app/src/main/java/org/fossasia/openevent/app/core/speakerscall/create/CreateSpeakersCallViewModel.java
app/src/test/java/org/fossasia/openevent/app/core/speakerscall/create/CreateSpeakersCallViewModelTest.java
app/src/test/java/org/fossasia/openevent/app/core/speakerscall/detail/SpeakersCallPresenterTest.java
app/src/test/java/org/fossasia/openevent/app/data/repository/SpeakersCallRepositoryTest.java

Fixes #1159
Checklist:
Changes: Added unit tests for SpeakersCallRepository, CreateSpeakersCallViewModel, SpeakersCallPresenter.

chore: Tests for SpeakersCall Module

---

app/src/main/java/org/fossasia/openevent/app/core/faq/create/CreateFaqFragment.java
app/src/main/java/org/fossasia/openevent/app/core/track/create/CreateTrackFragment.java

Fixes #1163 
Checklist:
Change: Hides keyboard when 'Submit' button clicked

fix: should hide keyboard when submit clicked

---

app/src/main/java/org/fossasia/openevent/app/core/orders/detail/OrderDetailViewModel.java
app/src/main/java/org/fossasia/openevent/app/core/orders/list/OrdersViewModel.java
app/src/test/java/org/fossasia/openevent/app/core/orders/detail/OrderDetailViewModelTest.java
app/src/test/java/org/fossasia/openevent/app/core/orders/list/OrdersViewModelTest.java
app/src/test/java/org/fossasia/openevent/app/data/repository/OrderRepositoryTest.java

Fixes #1168 
Checklist:
Changes: Added tests for OrdersRepository, OrdersViewModel, OrderDetailViewModel

chore: Added Tests for Order Module

---

app/build.gradle

Fixes #1177
Checklist:
Changes: 
1.  Refactored application id from `org.fossasia.eventyay` to `com.eventyay.organizer`.
2.  Updated app version.

chore: Changes for alpha v5 release

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/app/core/event/create/CreateEventViewModel.java
app/src/main/java/org/fossasia/openevent/app/core/event/create/EventDetailsStepThree.java
app/src/main/java/org/fossasia/openevent/app/core/event/create/EventDetailsStepTwo.java
app/src/main/java/org/fossasia/openevent/app/core/event/create/UpdateEventFragment.java
app/src/main/res/layout/create_event_activity.xml
app/src/main/res/layout/event_create_form.xml

Fixes #1180 
Checklist:
Changes:
1) Changed the status bar color as requested by changing the theme.
2) Now the information set in 2nd and 3rd step is visible in edit event process.
3) Checkboxes now show checked state in Edit event mode if they were checked during event creation.
4) Some indentation errors which were over looked earlier have also been resolved.

fix: Fix create event bugs

---

app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java
app/src/main/java/org/fossasia/openevent/app/core/auth/signup/SignUpFragment.java
app/src/main/java/org/fossasia/openevent/app/core/auth/signup/SignUpView.java
app/src/main/res/layout/sign_up_fragment.xml

Fixes #1191 
Checklist:
Changes: 

fix: Login and SignUp Error

---

app/build.gradle

chore: Changed Base URL

---

scripts/update-apk.sh

chore: Change APK name in update-apk.sh

---

app/build.gradle

Fixes #1209 
Checklist:
Changes: Updates versionCode and versionName

chore: increment versionCode

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/CreateCopyrightFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/copyright/update/UpdateCopyrightFragment.java
app/src/main/res/layout/about_event_activity.xml
app/src/main/res/layout/copyright_create_form.xml
app/src/main/res/layout/copyright_create_layout.xml

Fixes #1152 
Checklist:
Changes: 
1) Due to the collapsing bar layout the new fragment was taking an entire screen. I have added the main app bar layout in the about_event_activity.xml.
2) Also the create copyright screen was changed to make it consistent with the other create screens.

fix: Bug in Create Copyright fragment

---

app/src/main/java/org/fossasia/openevent/app/core/settings/SettingsFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

Fixes #1214 
Checklist:
Changes: 

feat: Added Option to Rate App

---

app/src/main/java/org/fossasia/openevent/app/core/settings/SettingsFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

Fixes #1215 
Checklist:
Changes: 

feat: Added Version Name in Device Settings

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/app/core/settings/SettingsFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
build.gradle

Fixes #1220 
Checklist:
Changes:  Added an acknowledgements section in Device Settings to view all the Open Source libraries used in the project. This section has been made similar to EventBrite.

feat: Add Acknowledgements section in Device Settings

---

app/src/main/java/org/fossasia/openevent/app/common/Runnable.java
app/src/main/java/org/fossasia/openevent/app/common/di/module/ChangeListenerModule.java
app/src/main/java/org/fossasia/openevent/app/core/event/dashboard/EventDashboardFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/dashboard/EventDashboardPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/event/dashboard/EventDashboardView.java
app/src/main/java/org/fossasia/openevent/app/ui/ViewUtils.java
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/org/fossasia/openevent/app/core/presenter/EventDashboardPresenterTest.java

Fixes #1223
Checklist:
Changes: 
1. Option to share event if published successfully.
2. Option to confirm to unpublish before unpublishing event.

feat: Dialog when publishing/unpublishing event

---

app/src/main/res/layout/event_details_step_three.xml

Fixes #1233 
Checklist:
Changes:

fix: Margin in Create Event Step three

---

app/src/main/java/org/fossasia/openevent/app/core/event/dashboard/EventDashboardFragment.java

fix: App crash on selecting Add location

---

app/src/main/java/org/fossasia/openevent/app/common/di/module/NetworkModule.java
app/src/main/java/org/fossasia/openevent/app/core/event/dashboard/EventDashboardFragment.java
app/src/main/java/org/fossasia/openevent/app/core/event/dashboard/EventDashboardPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/event/dashboard/EventDashboardView.java
app/src/main/java/org/fossasia/openevent/app/data/db/configuration/OrgaDatabase.java
app/src/main/java/org/fossasia/openevent/app/data/order/OrderApi.java
app/src/main/java/org/fossasia/openevent/app/data/order/OrderRepository.java
app/src/main/java/org/fossasia/openevent/app/data/order/OrderRepositoryImpl.java
app/src/main/java/org/fossasia/openevent/app/data/order/OrderStatistics.java
app/src/main/java/org/fossasia/openevent/app/data/order/Statistics.java
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/layout/order_statistics.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/core/presenter/EventDashboardPresenterTest.java

Fixes #1242 
Checklist:
Changes: 
1. Organizer can view Order and Sales statistics. (completed/total) %
2. Saving in Database for offline use.

feat: Add Order Statistics in Dashboard

---

.circleci/config.yml
.travis.yml
app/build.gradle
scripts/update-apk.sh

feat: Add product flavor for fdroid

---

app/src/main/java/org/fossasia/openevent/app/common/Constants.java
app/src/main/java/org/fossasia/openevent/app/core/attendee/qrscan/ScanQRActivity.java
app/src/main/java/org/fossasia/openevent/app/core/attendee/qrscan/ScanQRPresenter.java
app/src/main/java/org/fossasia/openevent/app/core/attendee/qrscan/ScanQRView.java
app/src/main/java/org/fossasia/openevent/app/core/settings/ScanSettings.java
app/src/main/res/values/strings.xml
app/src/test/java/org/fossasia/openevent/app/core/presenter/ScanQRPresenterTest.java

Fixes #1205 
Checklist:
Changes:
1. Implements use of scan settings in ScanQRActivity
2. Shows appropriate message instead of attendee id in panel
3. Changes colour based on ticket validity

feat: implement use of scanning preferences in ScanQRActivity

---

app/src/main/res/layout/bottomsheet_attendee_check_in.xml
app/src/main/res/values/strings.xml

Fixes #1252 
Checklist:
Changes: 

fix: Modifications in Attendee Detail UI

---

app/build.gradle
app/src/fdroid/java/org/fossasia/openevent/app/core/settings/AcknowledgementDecider.java
app/src/main/java/org/fossasia/openevent/app/core/settings/SettingsFragment.java
app/src/playStore/java/org/fossasia/openevent/app/core/settings/AcknowledgementDecider.java

Fixes #1255 
Checklist:
Changes: 
The OSS library dependency was remove from Fdroid release.

chore: Remove OSS from fdroid build

---

app/src/main/res/layout/event_details_step_one.xml
app/src/main/res/layout/event_details_step_three.xml
app/src/main/res/layout/event_details_step_two.xml

Fixes #1250 
Checklist:
Changes: Fixes inputType for form fields in Stepper

fix inputType for create event form fields

---

app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java

Fixes #1269 
Checklist:
Changes: 
1. Added Organizer detail in back stack.
2. Animations for fragment transaction.

fix: Bug in ChangePassword fragment back press

---

app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventActivity.java
app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventViewModel.java

Fixes #1271 
Checklist:
Changes: Verifies required fields in step 1 in step 1 only, and not after step 3.

fix: implement field validation for Event Creation Stepper-Step 1

---

app/src/main/res/layout/event_details_step_two.xml

Fixes #1273 
Checklist:
Changes: Adds padding and fixes indentation (GitHub diff looks messed up but only tab indents are added)

fix: Items in Step-2 Create Event should not hide, fix indent

---

app/src/main/java/com/eventyay/organizer/common/Constants.java
app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
app/src/main/java/com/eventyay/organizer/common/di/module/android/AuthFragmentBuildersModule.java
app/src/main/java/com/eventyay/organizer/core/auth/AuthActivity.java
app/src/main/java/com/eventyay/organizer/core/auth/login/LoginFragment.java
app/src/main/java/com/eventyay/organizer/core/auth/login/LoginView.java
app/src/main/java/com/eventyay/organizer/core/auth/login/LoginViewModel.java
app/src/main/java/com/eventyay/organizer/core/auth/reset/ResetPasswordFragment.java
app/src/main/java/com/eventyay/organizer/core/auth/signup/SignUpFragment.java
app/src/main/java/com/eventyay/organizer/core/auth/signup/SignUpView.java
app/src/main/java/com/eventyay/organizer/core/auth/start/StartFragment.java
app/src/main/java/com/eventyay/organizer/core/auth/start/StartView.java
app/src/main/java/com/eventyay/organizer/core/auth/start/StartViewModel.java
app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThree.java
app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThreeView.java
app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepTwo.java
app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepTwoView.java
app/src/main/java/com/eventyay/organizer/data/auth/AuthApi.java
app/src/main/java/com/eventyay/organizer/data/auth/AuthService.java
app/src/main/java/com/eventyay/organizer/data/auth/AuthServiceImpl.java
app/src/main/java/com/eventyay/organizer/data/auth/model/EmailRequest.java
app/src/main/java/com/eventyay/organizer/data/auth/model/EmailValidationResponse.java
app/src/main/java/com/eventyay/organizer/utils/ValidateUtils.java
app/src/main/res/layout/login_fragment.xml
app/src/main/res/layout/sign_up_fragment.xml
app/src/main/res/layout/start_fragment.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/eventyay/organizer/core/auth/login/LoginViewModelTest.java
app/src/test/java/com/eventyay/organizer/core/auth/start/StartViewModelTest.java

Fixes #1238 
Checklist:
Changes: Email check in a new Get Started screen, same as in the EventBrite app. If the email is registered, transitions to LogIn screen otherwise SignUp screen.

feat: add email registration check and StartFragment in AuthActivity

---

app/build.gradle

Fixes #1289 
Checklist:
Changes: 

chore: Changes for v1.0.6alpha release

---

app/src/main/res/layout/update_organizer_form.xml

Fixes #1294 
Checklist:
Changes: 

fix: Add MultiLine in UpdateOrganizerFragment

---

app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventActivity.java
app/src/main/java/com/eventyay/organizer/core/event/create/EventsViewPager.java
app/src/main/res/layout/create_event_activity.xml

fix: Disable swiping in ViewPager

---

app/src/main/res/layout/event_details_step_three.xml

feat: Remove Event state from Create Event

---

app/src/main/res/drawable/ic_camera.xml
app/src/main/res/layout/event_create_form.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #1306 
Checklist:
Changes: Adds image to update event screen

feat: Add event image to Update Event screen

---

app/src/main/res/layout/event_statistics.xml
app/src/main/res/layout/fragment_event_details.xml

Fixes #1310 
Checklist:
Changes: 

fix: Add Session Statistics Chart

---

app/build.gradle

Fixes #1323 
Checklist:
Changes: 

chore: Alpha v8 Release

---

README.md
docs/commitStyle.md

Fixes #1346 
Checklist:
Changes: [ commitStyle.md is added inside docs ]

docs: add commit style guidelines

---

README.md

chore: Update F-Droid Image link

---

README.md

Fixes #1336 
Checklist:
Changes:
- Add a README file in apk branch

chore: Add a README file in apk branch

---

app/build.gradle

chore: Change the base url in release version

---

README.md

update login credentials

---

app/src/main/java/com/eventyay/organizer/core/settings/SettingsFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

feat: Add share the app feature

---

README.md

Fixes #1405 
Checklist:
Changes: Under project conventions in the README fixed the grammar error where it said "There is certain conventions" to "There are certain conventions"

chore: grammar error in README is fixed

---

README.md
app/src/main/res/layout/event_statistics.xml
app/src/main/res/layout/fragment_event_details.xml
app/src/main/res/layout/order_statistics.xml

Fixes #1382 
Checklist:
Changes: UI fixes
Screenshots:
<table class="image">
<tr>
<td>Before<img src="https://user-images.githubusercontent.com/36705914/50415585-d6bb3400-0841-11e9-8db0-7f8a5cf3250b.png" alt="alt text" width="300"/></td>
<td>After<img src="https://user-images.githubusercontent.com/36705914/50452538-92728580-0960-11e9-98d4-1a1808a0ecac.png" alt="alt text" width="300"/></td>
</tr>
</table>

fix: UI fixes in Dashboard

---

app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventViewModel.java

Fixes #1404  
Error needs to displayed when user can't proceed
Checklist:
Changes: 
Now, error message would appear if user cannot proceed after step 3 of event creation.

fix: Display error if event creation fails

---

app/src/main/res/layout/update_organizer_form.xml

Fixes #1428 
Checklist:
Changes: 
Now, the email format will be validated to check if it's proper or not so that invalid things don't get accepted.

fix: Validate email format properly in Edit Profile

---

app/src/main/java/com/eventyay/organizer/core/ticket/create/CreateTicketFragment.java
app/src/main/java/com/eventyay/organizer/ui/ViewUtils.java

Fixes #1425 
Checklist:
Changes: 
Now, the Ticket Name field will have focus and keyboard will open when Create Ticket fragment is opened.

fix: Focus on Ticket Name and show keyboard when Create Ticket fragment is opened

---

app/src/main/res/layout/faqs_fragment.xml
app/src/main/res/layout/feedback_fragment.xml
app/src/main/res/layout/fragment_attendees.xml
app/src/main/res/layout/speakers_call_fragment.xml
app/src/main/res/layout/speakers_fragment.xml
app/src/main/res/layout/sponsors_fragment.xml
app/src/main/res/layout/tracks_fragment.xml

Fixes #1438 
Checklist:
Changes:
Now, the refresh icon will appear on swiping down in Attendees,  Feedback, FAQ, Tracks, Sponsors, Speakers, Speakers Call.

fix: Show refresh icon on swiping down

---

app/src/main/java/com/eventyay/organizer/ui/ViewUtils.java

Fixes #1470
Checklist:
Changes:
Changed neutral button of dialog box to positive button. 
Screenshot:

fix: Shift dialog box button to the right

---

app/src/main/java/com/eventyay/organizer/OrgaApplication.java

Fixes #1496 
Checklist:
Changes: 
Removed recursive calls to Timber.log in ReleaseLogTree

fix: Prevent recursive logging of bugs in release build

---

app/src/main/java/com/eventyay/organizer/core/session/create/CreateSessionPresenter.java

fix: nullify empty field while session update

---

app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesFragment.java
app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesPresenter.java
app/src/main/java/com/eventyay/organizer/core/attendee/list/SwipeController.java
app/src/main/java/com/eventyay/organizer/utils/Utils.java

Fixes #1130 
Checklist:
Changes: 
Now, swiping an attendee name in the list would toggle checkin and checkout state of the attendee.

feat: Implement swipe to checkin/checkout in Attendees list

---

app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java
app/src/main/res/layout/organizer_detail_layout.xml

Fixes #1527 
Checklist:
Changes: 
Made email, contact and all social links clickable with intents for opening the respective things.

feat: Clickable social links in organizer details

---

app/src/main/java/com/eventyay/organizer/core/auth/login/LoginFragment.java
app/src/main/java/com/eventyay/organizer/core/auth/login/LoginView.java
app/src/main/java/com/eventyay/organizer/core/auth/login/LoginViewModel.java

Fixes #1579 
Checklist:
Changes: 
Implemented LiveData for token request in a different way to prevent problem while going back from ResetPasswordFragment.

fix: Make ResetPasswordFragment exitable

---

.circleci/config.yml
.travis.yml
app/build.gradle
app/src/main/java/com/eventyay/organizer/data/attendee/AttendeeCheckInWork.java
build.gradle
gradle/wrapper/gradle-wrapper.properties
versions.gradle

Fixes #1547 
Checklist:
Changes: [Add here what changes were made in this issue and if possible provide links.]

chore(deps): Update gradle and dependencies

---

app/src/main/res/layout/bottomsheet_attendee_check_in.xml
app/src/main/res/values/strings.xml

Fixes #1609
Checklist:
Changes: 
Displays the attendee ID on the Check-in bottomsheet.

feat: Display Attendee ID on the Bottomsheet

---

README.md

Fixes #1615 
Checklist:
Changes: 
Uploaded the latest debug APK on Appetize.io and updated the link in README.md.

chore: Update Appetize.io preview link

---

app/src/main/java/com/eventyay/organizer/core/sponsor/list/SponsorsPresenter.java

Fixes #1552 
Checklist:
Changes: 
Now, Sponsors list will be updated on deletion of item.

fix: Refresh sponsors list automatically on deletion of items

---

app/src/main/java/com/eventyay/organizer/core/sponsor/list/SponsorsFragment.java
app/src/main/java/com/eventyay/organizer/core/sponsor/list/SponsorsPresenter.java

Fixes #1489 
Checklist:
Changes: 
Now, the list of sponsors would update automatically after creation of new sponsor.
GIF:

fix: Update sponsors list automatically on creation of new item

---

app/build.gradle
app/src/main/java/com/eventyay/organizer/common/di/AppInjector.java
app/src/main/java/com/eventyay/organizer/common/di/module/AppModule.java
app/src/main/java/com/eventyay/organizer/common/di/module/DatabaseModule.java
app/src/main/java/com/eventyay/organizer/core/faq/create/CreateFaqViewModel.java
app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java
app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListViewModel.java
app/src/main/java/com/eventyay/organizer/data/attendee/AttendeeCheckInWork.java
app/src/main/java/com/eventyay/organizer/data/db/configuration/EventIdConverter.java
app/src/main/java/com/eventyay/organizer/data/db/configuration/OrgaRoomDatabase.java
app/src/main/java/com/eventyay/organizer/data/faq/Faq.java
app/src/main/java/com/eventyay/organizer/data/faq/FaqDao.java
app/src/main/java/com/eventyay/organizer/data/faq/FaqRepository.java
app/src/main/java/com/eventyay/organizer/data/faq/FaqRepositoryImpl.java
app/src/test/java/com/eventyay/organizer/core/faq/create/CreateFaqViewModelTest.java
app/src/test/java/com/eventyay/organizer/core/faq/list/FaqListViewModelTest.java
app/src/test/java/com/eventyay/organizer/data/repository/FaqRepositoryTest.java
versions.gradle

Fixes #1653 
Checklist:
Changes: 
Implemented Room database and shifted FAQ module to Room.

chore: Migrate FAQ module to Room database

---

app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java
app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListViewModel.java

fix: Prevent unresponsive FAQ fragment issue

---

app/src/main/res/layout/event_create_form.xml

fix: Show correct state of map display checkbox

---

versions.gradle

chore: Set minimum required Android version to 5.0

---

app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
app/src/main/java/com/eventyay/organizer/core/attendee/qrscan/ScanQRViewModel.java
app/src/playStore/java/com/eventyay/organizer/core/attendee/qrscan/BarcodeDetected.java
app/src/playStore/java/com/eventyay/organizer/core/attendee/qrscan/ScanQRActivity.java
app/src/playStore/java/com/eventyay/organizer/core/attendee/qrscan/ScanQRView.java

chore: Convert ScanQRPresenter to ViewModel

---

app/src/main/java/com/eventyay/organizer/core/main/FragmentNavigator.java
app/src/main/java/com/eventyay/organizer/core/main/MainActivity.java
app/src/main/res/menu/activity_main_drawer.xml

chore: Simplify the app

---

app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java
app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListFragment.java
app/src/main/java/com/eventyay/organizer/core/role/list/RoleListFragment.java

fix: Prevent empty view layout from showing when items are present

---

app/src/main/res/layout/change_password_fragment.xml
app/src/main/res/layout/login_fragment.xml
app/src/main/res/layout/reset_password_by_token_fragment.xml
app/src/main/res/layout/sign_up_fragment.xml

fix: Retain password visibility state on screen rotation

---

app/src/main/java/com/eventyay/organizer/core/ticket/create/CreateTicketViewModel.java
app/src/test/java/com/eventyay/organizer/core/ticket/create/TicketCreateViewModelTest.java

Fixes #1720 
Checklist:
Changes: 
Event start date and time would now be used as the default ticket sale end date and time while creating tickets.

chore: Set event start time as default ticket sale end time

---

app/src/main/java/com/eventyay/organizer/core/main/DrawerNavigator.java
app/src/main/res/drawable/ic_account.xml
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/values/strings.xml

Fixes #1746 
Changes: 
Added 'My Account' below 'My Events' in navigation drawer.

feat: Add 'My Account' in navigation drawer

---

README.md

chore: Update README.md according to the change in repo name

---

app/src/fdroid/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java
app/src/fdroid/res/layout/event_create_form.xml
app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventActivity.java
app/src/main/java/com/eventyay/organizer/core/settings/EventSettingsFragment.java
app/src/main/java/com/eventyay/organizer/core/settings/PaymentPrefsFragment.java
app/src/main/res/layout/event_create_layout.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/event_preferences.xml

Fixes #1740 
Changes: 
Moved Payment Preferences from Event Settings to Edit Event.

chore: Move Payment Preferences to Edit Event

---

app/src/fdroid/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java
app/src/fdroid/res/layout/event_create_form.xml
app/src/fdroid/res/layout/event_details_step_one.xml
app/src/main/java/com/eventyay/organizer/data/db/configuration/OrgaDatabase.java
app/src/main/java/com/eventyay/organizer/data/event/Event.java
app/src/main/res/layout/about_event_detail.xml
app/src/playStore/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java
app/src/playStore/res/layout/event_create_form.xml
app/src/playStore/res/layout/event_details_step_one.xml

Fixes #1781 
Changes:
Updated fields according to changes in event model.

chore: Update event fields

---

app/src/main/java/com/eventyay/organizer/common/Constants.java
app/src/main/java/com/eventyay/organizer/core/auth/login/LoginFragment.java
app/src/main/java/com/eventyay/organizer/core/auth/login/LoginViewModel.java
app/src/main/java/com/eventyay/organizer/core/auth/reset/ResetPasswordFragment.java
app/src/main/java/com/eventyay/organizer/core/auth/reset/ResetPasswordViewModel.java
app/src/main/java/com/eventyay/organizer/core/auth/signup/SignUpFragment.java
app/src/main/java/com/eventyay/organizer/core/auth/signup/SignUpViewModel.java
app/src/main/java/com/eventyay/organizer/core/auth/start/StartFragment.java
app/src/main/java/com/eventyay/organizer/core/auth/start/StartViewModel.java
app/src/main/java/com/eventyay/organizer/core/organizer/password/ChangePasswordFragment.java
app/src/main/java/com/eventyay/organizer/core/organizer/password/ChangePasswordViewModel.java
app/src/main/res/layout/auth_url_container.xml
app/src/test/java/com/eventyay/organizer/core/auth/reset/ResetPasswordViewModelTest.java
app/src/test/java/com/eventyay/organizer/core/auth/signup/SignUpViewModelTest.java
app/src/test/java/com/eventyay/organizer/core/organizer/password/ChangePasswordViewModelTest.java

Fixes #1753 
**Changes:**
Now only 'Get Started' would show the option to change base URL and other authentication fragments would accordingly show the URL being used.
**GIF for the change:**

feat: Handle base URL in a better way

---

app/src/main/java/com/eventyay/organizer/core/event/list/EventListFragment.java

Fixes #690 
Changes: 
Now, list of events would be updated automatically after a new event is created.

fix: Update list of events automatically after creation of an event

---

scripts/update-apk.sh

fix: Use correct AAB filename

---

scripts/update-apk.sh

fix: Prevent error in APK generation

---

README.md

Fixes #1798 
Changes: 
Added 'Get it on F-Droid' badge to README.md.

chore: Add 'Get it on F-Droid' badge to README.md

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/eventyay/organizer/core/auth/AuthActivity.java
app/src/main/java/com/eventyay/organizer/core/auth/reset/ResetPasswordFragment.java
app/src/main/java/com/eventyay/organizer/core/auth/reset/ResetPasswordViewModel.java
app/src/main/java/com/eventyay/organizer/utils/LinkHandler.java
app/src/test/java/com/eventyay/organizer/utils/LinkHandlerTest.java

feat: Add app link for password reset

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailActivity.java
app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java
app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailViewModel.java
app/src/main/java/com/eventyay/organizer/data/auth/AuthApi.java
app/src/main/java/com/eventyay/organizer/data/auth/AuthService.java
app/src/main/java/com/eventyay/organizer/data/auth/AuthServiceImpl.java
app/src/main/java/com/eventyay/organizer/data/auth/model/EmailVerificationResponse.java
app/src/main/java/com/eventyay/organizer/data/auth/model/SubmitEmailVerificationToken.java
app/src/main/java/com/eventyay/organizer/utils/LinkHandler.java

Fixes #1801
Changes: 
Implemented email verification in app. Added app link so that email can be verified through app when user opens verification link sent via mail.

feat: Verify email with app

---

app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesViewModel.java

fix: Prevent adding of duplicate items on check-in

---

app/src/main/java/com/eventyay/organizer/core/organizer/update/UpdateOrganizerInfoFragment.java
app/src/main/res/layout/update_organizer_form.xml
app/src/main/res/values/strings.xml

chore: Improve Edit Profile section

---

app/src/main/res/layout/update_organizer_form.xml
app/src/main/res/layout/update_organizer_layout.xml

Fixes #1826 
Changes: 
Changed toolbar title to `Edit Profile`.

fix: Show correct title in Edit Profile section

---

app/src/main/java/com/eventyay/organizer/core/main/DrawerNavigator.java
app/src/main/res/menu/activity_main_drawer.xml

Fixes #1827 
Changes:
Commented out the 'Suggestions' option present in the navigation drawer.

chore: Remove Suggestions from navigation drawer

---

.travis.yml

chore: Fix travis build

---

fastlane/metadata/android/en-US/changelogs/15.txt

chore: Add fastlane changelog for v1.5.0

---

app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java
app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailViewModel.java
app/src/main/res/drawable/ic_delete_white.xml
app/src/main/res/layout/organizer_detail_layout.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml

feat: Option to delete profile picture

---

app/src/main/java/com/eventyay/organizer/core/event/about/AboutEventViewModel.java
app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardFragment.java
app/src/main/java/com/eventyay/organizer/utils/Utils.java

Fixes #1848 
Changes: 
Now, event link and location would also be shared along with other details.

chore: Share event link and location also

---

app/src/main/java/com/eventyay/organizer/core/event/list/EventListFragment.java
app/src/main/java/com/eventyay/organizer/core/event/list/pager/ListPageFragment.java
app/src/main/java/com/eventyay/organizer/core/main/EventViewModel.java
app/src/main/java/com/eventyay/organizer/core/main/FragmentNavigator.java
app/src/main/java/com/eventyay/organizer/core/main/MainActivity.java
app/src/main/java/com/eventyay/organizer/core/main/MainView.java
app/src/test/java/com/eventyay/organizer/core/main/FragmentNavigatorTest.java

chore: Improve navigation flow

---

app/src/main/java/com/eventyay/organizer/core/event/list/EventListFragment.java
app/src/main/java/com/eventyay/organizer/core/event/list/EventsViewModel.java
app/src/main/res/layout/event_list_fragment.xml

chore: Interchange 'Past' and 'Draft' sections in My Events

---

app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java
app/src/main/res/drawable/ic_phone.xml
app/src/main/res/layout/organizer_detail_layout.xml
app/src/main/res/menu/menu_organizer.xml
app/src/main/res/values/strings.xml

Fixes #1863 
Changes: 
- Moved phone to keep it with other profile details
- Added Change Password button and removed it from menu
- Renamed 'Contact' to 'Social Media Profiles'

chore: Improve Account section

---

app/src/main/java/com/eventyay/organizer/core/main/MainActivity.java

fix: Prevent app from closing while navigating back from Device Settings

---

app/src/main/res/layout/organizer_detail_layout.xml
app/src/main/res/values/strings.xml

Fixes #1877 
Changes: 
Renamed `Details` to `Profile` in organizer profile section.

chore: Rename 'Details' to 'Profile'

---

app/src/main/res/layout/update_organizer_form.xml
app/src/main/res/values/strings.xml

Fixes #1870 
Changes:
Added section for editing bio in `Edit Profile`.

feat: Add bio section in Edit Profile

---

app/src/main/java/com/eventyay/organizer/core/main/DrawerNavigator.java
app/src/main/java/com/eventyay/organizer/core/main/MainActivity.java
app/src/main/res/menu/activity_main_drawer.xml

Fixes #1880 
Changes:
Removed `About` section of event.

chore: Remove 'About' section of event

---

app/src/fdroid/java/com/eventyay/organizer/core/settings/AcknowledgementDecider.java
app/src/main/java/com/eventyay/organizer/common/di/module/android/MainFragmentBuildersModule.java
app/src/main/java/com/eventyay/organizer/core/about/AboutTheAppFragment.java
app/src/main/java/com/eventyay/organizer/core/main/FragmentNavigator.java
app/src/main/res/layout/about_the_app_fragment.xml
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/playStore/java/com/eventyay/organizer/core/settings/AcknowledgementDecider.java

feat: Add 'About The App' section

---

app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardFragment.java
app/src/main/java/com/eventyay/organizer/utils/DateUtils.java
app/src/main/res/layout/main_app_bar.xml
app/src/main/res/values/styles.xml

feat(ui): Add event name and time in dashboard

---

fastlane/metadata/android/en-US/changelogs/16.txt

Fixes #1888 
Added changelog for v1.6.0.

chore: Add changelog for v1.6.0

---

app/build.gradle
app/src/main/java/com/eventyay/organizer/ui/binding/BindingAdapters.java

chore: Update circularprogressbar version and fix errors

---

app/src/main/res/layout/event_statistics.xml

chore: Use confirmed speakers instead of accepted speakers

---

app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java

fix: Prevent Account section's action bar title from changing

---

app/src/main/res/layout/event_layout.xml
app/src/main/res/layout/fragment_event_details.xml

fix: Use correct values for tickets, sales and orders

---

app/src/main/java/com/eventyay/organizer/common/Constants.java
app/src/main/java/com/eventyay/organizer/common/di/module/NetworkModule.java
app/src/main/java/com/eventyay/organizer/data/auth/AuthHolder.java

fix: Use correct base URL in NetworkModule

---

app/src/main/res/layout/organizer_detail_layout.xml

fix: Hide contact and bio fields in organizer details if null

---

app/build.gradle

Updated version code to `17` and version name to `1.7.0`.

chore: Update version name and code for v1.7.0

---

app/src/main/java/com/eventyay/organizer/core/main/OrganizerViewModel.java
app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java

Fixes #1891 : Fixes username update on navigation drawer
Checklist:
Changes: 
Handled user object in live data

fix: username update on navigation drawer

---

app/src/main/java/com/eventyay/organizer/core/auth/start/StartFragment.java

fix: Use platform transitions to prevent crash
